#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Die Index-Seiten (measurements/, notes/, tools/) in neun Sprachen.

Gleiches Muster wie texte_startseite.py: ENGLISCH ist die Ausgangsfassung,
Rendering ueber build-indexseiten.py. Wer einen Eintrag ergaenzt oder aendert,
tut das HIER — die gebauten Seiten nicht von Hand editieren.

Hinweis „Deutsche Fassung auf derselben Seite": steht im Englischen und den
uebrigen Fremdsprachen drin, im Deutschen entfaellt er (da ist er gegenstandslos).
"""

SPRACHEN = ["en", "de", "es", "fr", "it", "ja", "pt-BR", "ru", "zh-CN"]
BASIS = "en"
SEITEN = ["measurements", "notes", "tools"]

TEXTE = {s: {} for s in SEITEN}

# ============================================================ MEASUREMENTS ====
TEXTE["measurements"]["en"] = {
    "h1": "Measurements",
    "lead": "Each one with the commands to repeat it, the raw data behind it, and a control run — because a method that does not fail where it should is not measuring anything.",
    "items": [
        {"date": "3 August 2026", "href": "install-an-extension-without-a-click/",
         "title": "Installing a browser extension without a click, and removing it again",
         "text": "Four routes, both directions, on an ordinary user account. Firefox's own Marionette channel installs and uninstalls a signed store build headless — and the two commands take a quarter of a second between them, so the cost is starting the browser, not the work. The click route reported success at every step and installed nothing.",
         "figures": ["<b>4.1 s</b> round trip", "<b>0.24 s</b> the commands themselves", "<b>0</b> input events", "<b>179 s</b> for the click route, which failed"]},
        {"date": "3 August 2026", "href": "de-plattformen/",
         "title": "German-language scholarly platforms measured: four read, seven handed back",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, the National Library, Springer, Nomos, beck-online, openJur, Statistik Austria and Destatis through the citation endpoint — with the failures named first and each reason measured, not guessed. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> complete records", "<b>1</b> measured wall", "<b>0</b> unreachable for a browser", "<b>0.75 s</b> per source"]},
        {"date": "3 August 2026", "href": "reading-list-to-bibliography/",
         "title": "Twenty links, ten citations: what a machine finishes and what it hands back",
         "text": "A reading list into a bibliography, end to end. Journal publishers yield records whether paywalled or open; statistics portals, chambers of commerce and newspapers yield none — and only one refusal in twenty was a bot defence.",
         "figures": ["<b>10/20</b> complete records", "<b>1</b> bot defence", "<b>5</b> pages with nothing to declare", "<b>0.4 s</b> per source"]},
        {"date": "3 August 2026", "href": "citation-triage/",
         "title": "An agent can cite eight of twelve sources — the useful part is knowing which four it cannot",
         "text": "A mixed reading list through a citation endpoint: complete records with RIS for two thirds, and the remaining third named precisely enough to fetch by hand.",
         "figures": ["<b>8/12</b> done by the agent", "<b>1.09 s</b> per source", "<b>4</b> named, not guessed"]},
        {"date": "3 August 2026", "href": "citation-by-platform/",
         "title": "Where citation data actually lives: 18 scholarly platforms measured",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex and thirteen more, each checked for what it declares about its own works — with every returned title verified against Crossref.",
         "figures": ["<b>11/18</b> returned data", "<b>10</b> with authors and year", "<b>8</b> matched Crossref"]},
        {"date": "2 August 2026", "href": "citation-extraction/",
         "title": "Measured against Citoid on random samples: same coverage, nothing invented",
         "text": "The Wikimedia service built on the Zotero translators is the yardstick. Across 18 works drawn at random: equal coverage, and no block reported as a success.",
         "figures": ["<b>13/13</b> fields complete", "<b>0</b> false block reports", "<b>0.35 s</b> median"]},
        {"date": "2 August 2026", "href": "android-capture-extensions/",
         "title": "Which page-saving extensions actually run on Firefox for Android?",
         "text": "248 extensions checked against the add-ons API. Chrome for Android cannot install any at all — so the question only arises on Firefox. Includes the correction of our own store listing.",
         "figures": ["<b>60</b> declare Android", "<b>85,724</b> users on the largest", "<b>0</b> tested on a device"]},
        {"date": "2 August 2026", "href": "web-citations-that-vanish/",
         "title": "Web citations that vanish: what happens to a source after you cite it",
         "text": "Why the retrieval date is in every reference list, what the research on link rot and content drift shows, and 150 cited sources checked for whether a copy exists anywhere. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19.3 %</b> gone", "<b>603 days</b> median archive age", "<b>2.0 %</b> unrecoverable"]},
        {"date": "1 August 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "Print to PDF or capture the screen? The same page measured both ways",
         "text": "Firefox already exports PDFs for free. The same article through both routes — including where print wins.",
         "figures": ["<b>1 : 26</b> pages", "<b>9</b> breaks cut a sentence", "capture: <b>91.5 %</b> recall"]},
        {"date": "1 August 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Webpage to PDF for OCR: how much text actually survives?",
         "text": "A screenshot PDF through Tesseract, compared against the source text, plus the resolution threshold where recognition collapses.",
         "figures": ["<b>92.6 %</b> recovered", "<b>8/8</b> critical values", "<b>72 dpi</b> collapse"]},
        {"date": "1 August 2026", "href": "pdf-extension-permissions/",
         "title": "Does your PDF extension upload the page?",
         "text": "What eight capture extensions declare in their manifests, how to check it in 30 seconds, and why server-side converters cannot reach a login.",
         "figures": ["<b>8</b> extensions", "raw data published"]},
        {"date": "1 August 2026", "href": "extension-permissions-risk/",
         "title": "An extension is only as dangerous as its permissions allow",
         "text": "One year after Mozilla warned about phished developer accounts: permission scope as blast radius, not as a trust signal.",
         "figures": ["worst-case table", "assessment checklist"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">About &amp; disclosure</a> · Corrections: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">Disclaimer</a>',
}

TEXTE["measurements"]["de"] = {
    "h1": "Messungen",
    "lead": "Jede mit den Befehlen zu ihrer Wiederholung, den Rohdaten dahinter und einem Kontrolllauf — denn eine Methode, die dort nicht scheitert, wo sie sollte, misst nichts.",
    "items": [
        {"date": "3. August 2026", "href": "install-an-extension-without-a-click/",
         "title": "Eine Browser-Erweiterung ohne Klick installieren — und wieder entfernen",
         "text": "Vier Wege, beide Richtungen, auf einem gewöhnlichen Benutzerkonto. Firefox' eigener Marionette-Kanal installiert und deinstalliert eine signierte Store-Version headless — und die zwei Befehle brauchen zusammen eine Viertelsekunde; die Kosten sind der Browser-Start, nicht die Arbeit. Der Klick-Weg meldete bei jedem Schritt Erfolg und installierte nichts.",
         "figures": ["<b>4,1 s</b> Hin- und Rückweg", "<b>0,24 s</b> die Befehle selbst", "<b>0</b> Eingabeereignisse", "<b>179 s</b> für den Klick-Weg, der scheiterte"]},
        {"date": "3. August 2026", "href": "de-plattformen/",
         "title": "Deutschsprachige wissenschaftliche Plattformen gemessen: vier gelesen, sieben zurückgegeben",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, die Nationalbibliothek, Springer, Nomos, beck-online, openJur, Statistik Austria und Destatis durch den Zitations-Endpunkt — mit den Fehlschlägen zuerst und jedem Grund gemessen, nicht vermutet.",
         "figures": ["<b>4/11</b> vollständige Datensätze", "<b>1</b> gemessene Mauer", "<b>0</b> für einen Browser unerreichbar", "<b>0,75 s</b> pro Quelle"]},
        {"date": "3. August 2026", "href": "reading-list-to-bibliography/",
         "title": "Zwanzig Links, zehn Zitationen: was eine Maschine fertig macht und was sie zurückgibt",
         "text": "Eine Leseliste in ein Literaturverzeichnis, von Anfang bis Ende. Fachverlage liefern Datensätze, ob Paywall oder offen; Statistikportale, Kammern und Zeitungen liefern keine — und nur eine Ablehnung von zwanzig war eine Bot-Abwehr.",
         "figures": ["<b>10/20</b> vollständige Datensätze", "<b>1</b> Bot-Abwehr", "<b>5</b> Seiten ohne etwas zu erklären", "<b>0,4 s</b> pro Quelle"]},
        {"date": "3. August 2026", "href": "citation-triage/",
         "title": "Ein Agent kann acht von zwölf Quellen zitieren — der nützliche Teil ist zu wissen, welche vier er nicht kann",
         "text": "Eine gemischte Leseliste durch einen Zitations-Endpunkt: vollständige Datensätze mit RIS für zwei Drittel, und das verbleibende Drittel präzise genug benannt, um es von Hand zu holen.",
         "figures": ["<b>8/12</b> vom Agenten erledigt", "<b>1,09 s</b> pro Quelle", "<b>4</b> benannt, nicht geraten"]},
        {"date": "3. August 2026", "href": "citation-by-platform/",
         "title": "Wo Zitationsdaten tatsächlich liegen: 18 wissenschaftliche Plattformen gemessen",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex und dreizehn weitere, jede geprüft darauf, was sie über ihre eigenen Werke erklärt — mit jedem zurückgegebenen Titel gegen Crossref verifiziert.",
         "figures": ["<b>11/18</b> lieferten Daten", "<b>10</b> mit Verfassern und Jahr", "<b>8</b> stimmten mit Crossref überein"]},
        {"date": "2. August 2026", "href": "citation-extraction/",
         "title": "Gegen Citoid an Zufallsstichproben gemessen: gleiche Abdeckung, nichts erfunden",
         "text": "Der Wikimedia-Dienst auf Basis der Zotero-Translatoren ist der Maßstab. Über 18 zufällig gezogene Werke: gleiche Abdeckung, und keine Sperre als Erfolg gemeldet.",
         "figures": ["<b>13/13</b> Felder vollständig", "<b>0</b> falsche Sperr-Meldungen", "<b>0,35 s</b> Median"]},
        {"date": "2. August 2026", "href": "android-capture-extensions/",
         "title": "Welche Seiten-Speicher-Erweiterungen laufen tatsächlich auf Firefox für Android?",
         "text": "248 Erweiterungen gegen die Add-ons-API geprüft. Chrome für Android kann überhaupt keine installieren — die Frage stellt sich also nur bei Firefox. Einschließlich der Korrektur unseres eigenen Store-Eintrags.",
         "figures": ["<b>60</b> deklarieren Android", "<b>85.724</b> Nutzer bei der größten", "<b>0</b> auf einem Gerät getestet"]},
        {"date": "2. August 2026", "href": "web-citations-that-vanish/",
         "title": "Web-Zitate, die verschwinden: was mit einer Quelle nach dem Zitieren passiert",
         "text": "Warum das Abrufdatum in jedes Literaturverzeichnis gehört, was die Forschung zu Linkverfall und Inhaltsdrift zeigt, und 150 zitierte Quellen geprüft darauf, ob irgendwo eine Kopie existiert.",
         "figures": ["<b>19,3 %</b> verschwunden", "<b>603 Tage</b> medianes Archivalter", "<b>2,0 %</b> unwiederbringlich"]},
        {"date": "1. August 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "Als PDF drucken oder den Bildschirm aufnehmen? Dieselbe Seite, beide Wege gemessen",
         "text": "Firefox exportiert bereits kostenlos PDFs. Derselbe Artikel durch beide Wege — einschließlich der Stelle, an der der Druck gewinnt.",
         "figures": ["<b>1 : 26</b> Seiten", "<b>9</b> Umbrüche durchtrennen einen Satz", "Aufnahme: <b>91,5 %</b> Treffer"]},
        {"date": "1. August 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Webseite als PDF für OCR: Wie viel Text überlebt tatsächlich?",
         "text": "Ein Screenshot-PDF durch Tesseract, verglichen mit dem Ursprungstext, dazu die Auflösungsschwelle, an der die Erkennung einbricht.",
         "figures": ["<b>92,6 %</b> zurückgewonnen", "<b>8/8</b> kritische Werte", "<b>72 dpi</b> Einbruch"]},
        {"date": "1. August 2026", "href": "pdf-extension-permissions/",
         "title": "Lädt Ihre PDF-Erweiterung die Seite hoch?",
         "text": "Was acht Aufnahme-Erweiterungen in ihren Manifesten deklarieren, wie man es in 30 Sekunden prüft, und warum server-seitige Konverter kein Login erreichen.",
         "figures": ["<b>8</b> Erweiterungen", "Rohdaten veröffentlicht"]},
        {"date": "1. August 2026", "href": "extension-permissions-risk/",
         "title": "Eine Erweiterung ist nur so gefährlich, wie ihre Berechtigungen es erlauben",
         "text": "Ein Jahr nach Mozillas Warnung vor erbeuteten Entwicklerkonten: Berechtigungsumfang als Wirkungsradius, nicht als Vertrauenssignal.",
         "figures": ["Worst-Case-Tabelle", "Bewertungs-Checkliste"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Über &amp; Offenlegung</a> · Korrekturen: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub Issues</a> · <a href="../disclaimer/">Haftungsausschluss</a>',
}

TEXTE["measurements"]["es"] = {
    "h1": "Mediciones",
    "lead": "Cada una con los comandos para repetirla, los datos brutos detrás y una ejecución de control — porque un método que no falla donde debería no está midiendo nada.",
    "items": [
        {"date": "3 de agosto de 2026", "href": "install-an-extension-without-a-click/",
         "title": "Instalar una extensión de navegador sin un clic, y quitarla de nuevo",
         "text": "Cuatro vías, en ambas direcciones, en una cuenta de usuario normal. El canal Marionette del propio Firefox instala y desinstala una compilación firmada de la tienda sin ventana — y los dos comandos tardan un cuarto de segundo entre ambos; el coste es arrancar el navegador, no el trabajo. La vía del clic informó éxito en cada paso y no instaló nada.",
         "figures": ["<b>4,1 s</b> ida y vuelta", "<b>0,24 s</b> los comandos en sí", "<b>0</b> eventos de entrada", "<b>179 s</b> para la vía del clic, que falló"]},
        {"date": "3 de agosto de 2026", "href": "de-plattformen/",
         "title": "Plataformas académicas en alemán medidas: cuatro leídas, siete devueltas",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, la Biblioteca Nacional, Springer, Nomos, beck-online, openJur, Statistik Austria y Destatis por el endpoint de citación — con los fallos nombrados primero y cada razón medida, no supuesta. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> registros completos", "<b>1</b> muro medido", "<b>0</b> inalcanzables para un navegador", "<b>0,75 s</b> por fuente"]},
        {"date": "3 de agosto de 2026", "href": "reading-list-to-bibliography/",
         "title": "Veinte enlaces, diez citas: qué termina una máquina y qué devuelve",
         "text": "Una lista de lectura convertida en bibliografía, de principio a fin. Las editoriales científicas dan registros, con muro de pago o abiertas; los portales de estadística, las cámaras de comercio y los periódicos no dan ninguno — y solo una negativa de veinte fue una defensa contra bots.",
         "figures": ["<b>10/20</b> registros completos", "<b>1</b> defensa contra bots", "<b>5</b> páginas sin nada que declarar", "<b>0,4 s</b> por fuente"]},
        {"date": "3 de agosto de 2026", "href": "citation-triage/",
         "title": "Un agente puede citar ocho de doce fuentes — lo útil es saber cuáles cuatro no puede",
         "text": "Una lista de lectura mixta por un endpoint de citación: registros completos con RIS para dos tercios, y el tercio restante nombrado con la precisión suficiente para buscarlo a mano.",
         "figures": ["<b>8/12</b> hechas por el agente", "<b>1,09 s</b> por fuente", "<b>4</b> nombradas, no adivinadas"]},
        {"date": "3 de agosto de 2026", "href": "citation-by-platform/",
         "title": "Dónde viven realmente los datos de citación: 18 plataformas académicas medidas",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex y trece más, cada una comprobada por lo que declara sobre sus propias obras — con cada título devuelto verificado contra Crossref.",
         "figures": ["<b>11/18</b> devolvieron datos", "<b>10</b> con autores y año", "<b>8</b> coincidieron con Crossref"]},
        {"date": "2 de agosto de 2026", "href": "citation-extraction/",
         "title": "Medido contra Citoid en muestras aleatorias: misma cobertura, nada inventado",
         "text": "El servicio de Wikimedia construido sobre los traductores de Zotero es el patrón. En 18 obras extraídas al azar: cobertura igual, y ningún bloqueo informado como éxito.",
         "figures": ["<b>13/13</b> campos completos", "<b>0</b> informes de bloqueo falsos", "<b>0,35 s</b> de mediana"]},
        {"date": "2 de agosto de 2026", "href": "android-capture-extensions/",
         "title": "¿Qué extensiones de guardado de páginas funcionan realmente en Firefox para Android?",
         "text": "248 extensiones comprobadas contra la API de complementos. Chrome para Android no puede instalar ninguna — así que la pregunta solo surge en Firefox. Incluye la corrección de nuestro propio listado de la tienda.",
         "figures": ["<b>60</b> declaran Android", "<b>85.724</b> usuarios en la mayor", "<b>0</b> probadas en un dispositivo"]},
        {"date": "2 de agosto de 2026", "href": "web-citations-that-vanish/",
         "title": "Citas web que desaparecen: qué pasa con una fuente después de citarla",
         "text": "Por qué la fecha de consulta está en toda bibliografía, qué muestra la investigación sobre podredumbre de enlaces y deriva de contenido, y 150 fuentes citadas comprobadas por si existe una copia en algún sitio. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19,3 %</b> desaparecidas", "<b>603 días</b> de edad mediana del archivo", "<b>2,0 %</b> irrecuperables"]},
        {"date": "1 de agosto de 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "¿Imprimir a PDF o capturar la pantalla? La misma página medida de ambas formas",
         "text": "Firefox ya exporta PDF gratis. El mismo artículo por ambas vías — incluido dónde gana la impresión.",
         "figures": ["<b>1 : 26</b> páginas", "<b>9</b> saltos cortan una frase", "captura: <b>91,5 %</b> de recuperación"]},
        {"date": "1 de agosto de 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Página web a PDF para OCR: ¿cuánto texto sobrevive realmente?",
         "text": "Un PDF de captura por Tesseract, comparado con el texto fuente, más el umbral de resolución donde el reconocimiento colapsa.",
         "figures": ["<b>92,6 %</b> recuperado", "<b>8/8</b> valores críticos", "<b>72 dpi</b> colapso"]},
        {"date": "1 de agosto de 2026", "href": "pdf-extension-permissions/",
         "title": "¿Sube tu extensión de PDF la página?",
         "text": "Qué declaran ocho extensiones de captura en sus manifiestos, cómo comprobarlo en 30 segundos, y por qué los conversores del lado del servidor no alcanzan un inicio de sesión.",
         "figures": ["<b>8</b> extensiones", "datos brutos publicados"]},
        {"date": "1 de agosto de 2026", "href": "extension-permissions-risk/",
         "title": "Una extensión solo es tan peligrosa como sus permisos permiten",
         "text": "Un año después de la advertencia de Mozilla sobre cuentas de desarrollador robadas: el alcance de los permisos como radio de daño, no como señal de confianza.",
         "figures": ["tabla del peor caso", "lista de verificación"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Acerca de &amp; divulgación</a> · Correcciones: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues de GitHub</a> · <a href="../disclaimer/">Aviso legal</a>',
}

TEXTE["measurements"]["fr"] = {
    "h1": "Mesures",
    "lead": "Chacune avec les commandes pour la refaire, les données brutes derrière, et un essai de contrôle — car une méthode qui n'échoue pas là où elle le devrait ne mesure rien.",
    "items": [
        {"date": "3 août 2026", "href": "install-an-extension-without-a-click/",
         "title": "Installer une extension de navigateur sans un clic, et la retirer ensuite",
         "text": "Quatre voies, dans les deux sens, sur un compte utilisateur ordinaire. Le canal Marionette de Firefox installe et désinstalle une version signée de la boutique sans fenêtre — et les deux commandes prennent un quart de seconde à elles deux ; le coût est le démarrage du navigateur, pas le travail. La voie du clic a annoncé un succès à chaque étape et n'a rien installé.",
         "figures": ["<b>4,1 s</b> aller-retour", "<b>0,24 s</b> les commandes elles-mêmes", "<b>0</b> événement de saisie", "<b>179 s</b> pour la voie du clic, qui a échoué"]},
        {"date": "3 août 2026", "href": "de-plattformen/",
         "title": "Plates-formes savantes germanophones mesurées : quatre lues, sept rendues",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, la Bibliothèque nationale, Springer, Nomos, beck-online, openJur, Statistik Austria et Destatis par le point d'accès de citation — avec les échecs nommés d'abord et chaque raison mesurée, pas supposée. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> notices complètes", "<b>1</b> mur mesuré", "<b>0</b> inaccessible à un navigateur", "<b>0,75 s</b> par source"]},
        {"date": "3 août 2026", "href": "reading-list-to-bibliography/",
         "title": "Vingt liens, dix citations : ce qu'une machine termine et ce qu'elle rend",
         "text": "Une liste de lecture transformée en bibliographie, de bout en bout. Les éditeurs scientifiques fournissent des notices, avec ou sans mur payant ; les portails de statistique, les chambres de commerce et les journaux n'en fournissent aucune — et un seul refus sur vingt était une défense anti-robots.",
         "figures": ["<b>10/20</b> notices complètes", "<b>1</b> défense anti-robots", "<b>5</b> pages sans rien à déclarer", "<b>0,4 s</b> par source"]},
        {"date": "3 août 2026", "href": "citation-triage/",
         "title": "Un agent peut citer huit sources sur douze — l'utile est de savoir quelles quatre il ne peut pas",
         "text": "Une liste de lecture mixte par un point d'accès de citation : des notices complètes avec RIS pour les deux tiers, et le tiers restant nommé assez précisément pour aller le chercher à la main.",
         "figures": ["<b>8/12</b> faites par l'agent", "<b>1,09 s</b> par source", "<b>4</b> nommées, pas devinées"]},
        {"date": "3 août 2026", "href": "citation-by-platform/",
         "title": "Où vivent vraiment les données de citation : 18 plates-formes savantes mesurées",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex et treize autres, chacune vérifiée sur ce qu'elle déclare de ses propres œuvres — avec chaque titre rendu vérifié contre Crossref.",
         "figures": ["<b>11/18</b> ont rendu des données", "<b>10</b> avec auteurs et année", "<b>8</b> concordantes avec Crossref"]},
        {"date": "2 août 2026", "href": "citation-extraction/",
         "title": "Mesuré contre Citoid sur échantillons aléatoires : même couverture, rien d'inventé",
         "text": "Le service Wikimedia bâti sur les traducteurs Zotero fait office d'étalon. Sur 18 œuvres tirées au hasard : couverture égale, et aucun blocage rapporté comme un succès.",
         "figures": ["<b>13/13</b> champs complets", "<b>0</b> faux rapport de blocage", "<b>0,35 s</b> de médiane"]},
        {"date": "2 août 2026", "href": "android-capture-extensions/",
         "title": "Quelles extensions de sauvegarde de page tournent vraiment sur Firefox pour Android ?",
         "text": "248 extensions vérifiées contre l'API des modules. Chrome pour Android ne peut en installer aucune — la question ne se pose donc que sur Firefox. Y compris la correction de notre propre fiche de boutique.",
         "figures": ["<b>60</b> déclarent Android", "<b>85 724</b> utilisateurs sur la plus grosse", "<b>0</b> testée sur un appareil"]},
        {"date": "2 août 2026", "href": "web-citations-that-vanish/",
         "title": "Citations web qui disparaissent : ce qu'il advient d'une source après l'avoir citée",
         "text": "Pourquoi la date de consultation figure dans toute bibliographie, ce que montre la recherche sur la pourriture des liens et la dérive des contenus, et 150 sources citées vérifiées pour savoir si une copie existe quelque part. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19,3 %</b> disparues", "<b>603 jours</b> d'âge médian d'archive", "<b>2,0 %</b> irrécupérables"]},
        {"date": "1 août 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "Imprimer en PDF ou capturer l'écran ? La même page mesurée des deux façons",
         "text": "Firefox exporte déjà des PDF gratuitement. Le même article par les deux voies — y compris là où l'impression gagne.",
         "figures": ["<b>1 : 26</b> pages", "<b>9</b> sauts coupent une phrase", "capture : <b>91,5 %</b> de rappel"]},
        {"date": "1 août 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Page web en PDF pour l'OCR : combien de texte survit vraiment ?",
         "text": "Un PDF de capture passé dans Tesseract, comparé au texte source, plus le seuil de résolution où la reconnaissance s'effondre.",
         "figures": ["<b>92,6 %</b> récupéré", "<b>8/8</b> valeurs critiques", "<b>72 dpi</b> effondrement"]},
        {"date": "1 août 2026", "href": "pdf-extension-permissions/",
         "title": "Votre extension PDF téléverse-t-elle la page ?",
         "text": "Ce que huit extensions de capture déclarent dans leurs manifestes, comment le vérifier en 30 secondes, et pourquoi les convertisseurs côté serveur n'atteignent pas un identifiant.",
         "figures": ["<b>8</b> extensions", "données brutes publiées"]},
        {"date": "1 août 2026", "href": "extension-permissions-risk/",
         "title": "Une extension n'est dangereuse que dans la mesure de ses permissions",
         "text": "Un an après l'avertissement de Mozilla sur les comptes de développeur volés : la portée des permissions comme rayon de dommage, pas comme signal de confiance.",
         "figures": ["tableau du pire cas", "liste de contrôle"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">À propos &amp; transparence</a> · Corrections : <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">tickets GitHub</a> · <a href="../disclaimer/">Mentions légales</a>',
}

TEXTE["measurements"]["it"] = {
    "h1": "Misurazioni",
    "lead": "Ognuna con i comandi per ripeterla, i dati grezzi alle spalle e una prova di controllo — perché un metodo che non fallisce dove dovrebbe non sta misurando nulla.",
    "items": [
        {"date": "3 agosto 2026", "href": "install-an-extension-without-a-click/",
         "title": "Installare un'estensione del browser senza un clic, e rimuoverla di nuovo",
         "text": "Quattro vie, in entrambe le direzioni, su un normale account utente. Il canale Marionette di Firefox installa e disinstalla una build firmata dello store senza finestra — e i due comandi impiegano un quarto di secondo in due; il costo è avviare il browser, non il lavoro. La via del clic ha riportato successo a ogni passo e non ha installato nulla.",
         "figures": ["<b>4,1 s</b> andata e ritorno", "<b>0,24 s</b> i comandi stessi", "<b>0</b> eventi di input", "<b>179 s</b> per la via del clic, fallita"]},
        {"date": "3 agosto 2026", "href": "de-plattformen/",
         "title": "Piattaforme accademiche di lingua tedesca misurate: quattro lette, sette restituite",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, la Biblioteca Nazionale, Springer, Nomos, beck-online, openJur, Statistik Austria e Destatis attraverso l'endpoint di citazione — con i fallimenti nominati per primi e ogni ragione misurata, non supposta. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> record completi", "<b>1</b> muro misurato", "<b>0</b> irraggiungibili per un browser", "<b>0,75 s</b> per fonte"]},
        {"date": "3 agosto 2026", "href": "reading-list-to-bibliography/",
         "title": "Venti link, dieci citazioni: cosa completa una macchina e cosa restituisce",
         "text": "Una lista di lettura trasformata in bibliografia, dall'inizio alla fine. Gli editori scientifici danno record, con paywall o aperti; i portali di statistica, le camere di commercio e i quotidiani non ne danno nessuno — e solo un rifiuto su venti era una difesa anti-bot.",
         "figures": ["<b>10/20</b> record completi", "<b>1</b> difesa anti-bot", "<b>5</b> pagine senza nulla da dichiarare", "<b>0,4 s</b> per fonte"]},
        {"date": "3 agosto 2026", "href": "citation-triage/",
         "title": "Un agente può citare otto fonti su dodici — la parte utile è sapere quali quattro non può",
         "text": "Una lista di lettura mista attraverso un endpoint di citazione: record completi con RIS per due terzi, e il terzo rimanente nominato con precisione sufficiente per recuperarlo a mano.",
         "figures": ["<b>8/12</b> fatte dall'agente", "<b>1,09 s</b> per fonte", "<b>4</b> nominate, non indovinate"]},
        {"date": "3 agosto 2026", "href": "citation-by-platform/",
         "title": "Dove vivono davvero i dati di citazione: 18 piattaforme accademiche misurate",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex e altre tredici, ognuna controllata su ciò che dichiara delle proprie opere — con ogni titolo restituito verificato contro Crossref.",
         "figures": ["<b>11/18</b> hanno restituito dati", "<b>10</b> con autori e anno", "<b>8</b> corrispondenti a Crossref"]},
        {"date": "2 agosto 2026", "href": "citation-extraction/",
         "title": "Misurato contro Citoid su campioni casuali: stessa copertura, nulla di inventato",
         "text": "Il servizio Wikimedia costruito sui traduttori di Zotero è il riferimento. Su 18 opere estratte a caso: copertura uguale, e nessun blocco riportato come successo.",
         "figures": ["<b>13/13</b> campi completi", "<b>0</b> falsi rapporti di blocco", "<b>0,35 s</b> di mediana"]},
        {"date": "2 agosto 2026", "href": "android-capture-extensions/",
         "title": "Quali estensioni di salvataggio pagine funzionano davvero su Firefox per Android?",
         "text": "248 estensioni controllate contro l'API dei componenti aggiuntivi. Chrome per Android non ne può installare nessuna — quindi la domanda si pone solo su Firefox. Include la correzione della nostra stessa scheda dello store.",
         "figures": ["<b>60</b> dichiarano Android", "<b>85.724</b> utenti sulla più grande", "<b>0</b> testate su un dispositivo"]},
        {"date": "2 agosto 2026", "href": "web-citations-that-vanish/",
         "title": "Citazioni web che spariscono: cosa succede a una fonte dopo averla citata",
         "text": "Perché la data di consultazione è in ogni bibliografia, cosa mostra la ricerca su link rot e content drift, e 150 fonti citate controllate per vedere se esiste una copia da qualche parte. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19,3 %</b> sparite", "<b>603 giorni</b> di età mediana dell'archivio", "<b>2,0 %</b> irrecuperabili"]},
        {"date": "1 agosto 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "Stampare in PDF o catturare lo schermo? La stessa pagina misurata in entrambi i modi",
         "text": "Firefox esporta già PDF gratis. Lo stesso articolo per entrambe le vie — incluso dove vince la stampa.",
         "figures": ["<b>1 : 26</b> pagine", "<b>9</b> interruzioni tagliano una frase", "cattura: <b>91,5 %</b> di richiamo"]},
        {"date": "1 agosto 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Pagina web in PDF per OCR: quanto testo sopravvive davvero?",
         "text": "Un PDF di cattura in Tesseract, confrontato con il testo sorgente, più la soglia di risoluzione in cui il riconoscimento crolla.",
         "figures": ["<b>92,6 %</b> recuperato", "<b>8/8</b> valori critici", "<b>72 dpi</b> collasso"]},
        {"date": "1 agosto 2026", "href": "pdf-extension-permissions/",
         "title": "La tua estensione PDF carica la pagina?",
         "text": "Cosa dichiarano otto estensioni di cattura nei loro manifest, come controllarlo in 30 secondi, e perché i convertitori lato server non raggiungono un login.",
         "figures": ["<b>8</b> estensioni", "dati grezzi pubblicati"]},
        {"date": "1 agosto 2026", "href": "extension-permissions-risk/",
         "title": "Un'estensione è pericolosa solo quanto i suoi permessi consentono",
         "text": "Un anno dopo l'avvertimento di Mozilla sugli account sviluppatore rubati: la portata dei permessi come raggio di danno, non come segnale di fiducia.",
         "figures": ["tabella del caso peggiore", "checklist di valutazione"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Informazioni &amp; trasparenza</a> · Correzioni: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issue su GitHub</a> · <a href="../disclaimer/">Esclusione di responsabilità</a>',
}

TEXTE["measurements"]["ja"] = {
    "h1": "測定",
    "lead": "それぞれに、再現するためのコマンド、背後の生データ、そしてコントロールランがあります — 失敗すべきところで失敗しない方法は、何も測っていないからです。",
    "items": [
        {"date": "2026年8月3日", "href": "install-an-extension-without-a-click/",
         "title": "クリックなしでブラウザ拡張機能をインストールし、再び削除する",
         "text": "4つの経路、双方向、一般ユーザーアカウントで。Firefox 自身の Marionette チャネルが署名済みストアビルドをヘッドレスでインストール・アンインストールし — 2つのコマンドは合わせて4分の1秒。コストはブラウザの起動であって作業ではありません。クリック経路はすべてのステップで成功と報告し、何もインストールしませんでした。",
         "figures": ["往復 <b>4.1秒</b>", "コマンド自体は <b>0.24秒</b>", "入力イベント <b>0</b>", "失敗したクリック経路は <b>179秒</b>"]},
        {"date": "2026年8月3日", "href": "de-plattformen/",
         "title": "ドイツ語の学術プラットフォームを測定: 4件は読め、7件は返却",
         "text": "SSOAR、PsychArchives、peDOCS、OPUS、国立図書館、Springer、Nomos、beck-online、openJur、Statistik Austria、Destatis を引用エンドポイントに通し — 失敗を先に挙げ、各理由を推測ではなく測定。Deutsche Fassung auf derselben Seite.",
         "figures": ["完全なレコード <b>4/11</b>", "測定された壁 <b>1</b>", "ブラウザで届かないもの <b>0</b>", "1ソースあたり <b>0.75秒</b>"]},
        {"date": "2026年8月3日", "href": "reading-list-to-bibliography/",
         "title": "20のリンク、10の引用: 機械が終わらせるものと、返すもの",
         "text": "読書リストを参考文献に、最初から最後まで。学術出版社はペイウォールでもオープンでもレコードを返します。統計ポータル、商工会議所、新聞は何も返しません — 20件中の拒否でボット防御だったのは1件だけでした。",
         "figures": ["完全なレコード <b>10/20</b>", "ボット防御 <b>1</b>", "宣言するものがないページ <b>5</b>", "1ソースあたり <b>0.4秒</b>"]},
        {"date": "2026年8月3日", "href": "citation-triage/",
         "title": "エージェントは12件中8件を引用できる — 有用なのは、できない4件が分かること",
         "text": "混合の読書リストを引用エンドポイントに通しました: 3分の2は RIS 付きの完全なレコード、残りの3分の1は手で取得できるだけ正確に名前が挙がっています。",
         "figures": ["エージェントが処理 <b>8/12</b>", "1ソースあたり <b>1.09秒</b>", "推測でなく指名 <b>4</b>"]},
        {"date": "2026年8月3日", "href": "citation-by-platform/",
         "title": "引用データは実際どこにあるか: 18の学術プラットフォームを測定",
         "text": "PubMed、arXiv、Zenodo、SSRN、EUR-Lex ほか13件。それぞれが自らの著作について何を宣言しているかを確認し — 返されたすべてのタイトルを Crossref と照合しました。",
         "figures": ["データを返した <b>11/18</b>", "著者と年がある <b>10</b>", "Crossref と一致 <b>8</b>"]},
        {"date": "2026年8月2日", "href": "citation-extraction/",
         "title": "ランダムサンプルで Citoid と比較測定: 同じカバレッジ、捏造なし",
         "text": "Zotero トランスレーター上に構築された Wikimedia のサービスが物差しです。ランダムに抽出した18の著作で: カバレッジは同等、ブロックを成功と報告したことはありません。",
         "figures": ["フィールド完全 <b>13/13</b>", "誤ったブロック報告 <b>0</b>", "中央値 <b>0.35秒</b>"]},
        {"date": "2026年8月2日", "href": "android-capture-extensions/",
         "title": "ページ保存拡張機能で、実際に Android 版 Firefox で動くのはどれか?",
         "text": "248の拡張機能をアドオン API と照合。Android 版 Chrome は一切インストールできません — だからこの問いは Firefox でのみ生じます。私たち自身のストア掲載の修正も含まれます。",
         "figures": ["Android 対応を宣言 <b>60</b>", "最大のものでユーザー <b>85,724</b>", "実機でテスト済み <b>0</b>"]},
        {"date": "2026年8月2日", "href": "web-citations-that-vanish/",
         "title": "消えるウェブ引用: 引用したあと、ソースに何が起こるか",
         "text": "なぜ取得日がすべての参考文献に必要か、リンクロットと内容漂流の研究が示すこと、そして引用された150のソースについて、どこかにコピーがあるかを確認。Deutsche Fassung auf derselben Seite.",
         "figures": ["消失 <b>19.3%</b>", "アーカイブ年齢の中央値 <b>603日</b>", "回復不能 <b>2.0%</b>"]},
        {"date": "2026年8月1日", "href": "print-to-pdf-vs-screenshot/",
         "title": "PDF に印刷するか、画面をキャプチャするか? 同じページを両方の方法で測定",
         "text": "Firefox はすでに無料で PDF をエクスポートできます。同じ記事を両方の経路で — 印刷が勝るところも含めて。",
         "figures": ["ページ数 <b>1 : 26</b>", "文を断ち切る改ページ <b>9</b>", "キャプチャ: 再現率 <b>91.5%</b>"]},
        {"date": "2026年8月1日", "href": "webpage-to-pdf-for-ocr/",
         "title": "OCR のためのウェブページ PDF 化: 実際にどれだけのテキストが残るか?",
         "text": "スクリーンショット PDF を Tesseract にかけ、ソーステキストと比較。認識が崩壊する解像度の閾値も。",
         "figures": ["回復 <b>92.6%</b>", "重要な値 <b>8/8</b>", "崩壊 <b>72 dpi</b>"]},
        {"date": "2026年8月1日", "href": "pdf-extension-permissions/",
         "title": "あなたの PDF 拡張機能はページをアップロードしていますか?",
         "text": "8つのキャプチャ拡張機能がマニフェストで宣言していること、30秒で確認する方法、そしてサーバーサイドのコンバーターがログインに届かない理由。",
         "figures": ["拡張機能 <b>8</b> 件", "生データ公開済み"]},
        {"date": "2026年8月1日", "href": "extension-permissions-risk/",
         "title": "拡張機能は、その権限が許す範囲でしか危険にならない",
         "text": "Mozilla が開発者アカウントのフィッシングを警告してから1年: 権限の範囲は信頼のシグナルではなく、被害半径として。",
         "figures": ["最悪ケース表", "評価チェックリスト"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">概要と開示</a> · 修正: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">免責事項</a>',
}

TEXTE["measurements"]["pt-BR"] = {
    "h1": "Medições",
    "lead": "Cada uma com os comandos para repeti-la, os dados brutos por trás e uma execução de controle — porque um método que não falha onde deveria não está medindo nada.",
    "items": [
        {"date": "3 de agosto de 2026", "href": "install-an-extension-without-a-click/",
         "title": "Instalar uma extensão de navegador sem um clique, e removê-la de novo",
         "text": "Quatro vias, nas duas direções, numa conta de usuário comum. O canal Marionette do próprio Firefox instala e desinstala uma versão assinada da loja sem janela — e os dois comandos levam um quarto de segundo juntos; o custo é iniciar o navegador, não o trabalho. A via do clique relatou sucesso em cada passo e não instalou nada.",
         "figures": ["<b>4,1 s</b> ida e volta", "<b>0,24 s</b> os comandos em si", "<b>0</b> eventos de entrada", "<b>179 s</b> para a via do clique, que falhou"]},
        {"date": "3 de agosto de 2026", "href": "de-plattformen/",
         "title": "Plataformas acadêmicas em alemão medidas: quatro lidas, sete devolvidas",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, a Biblioteca Nacional, Springer, Nomos, beck-online, openJur, Statistik Austria e Destatis pelo endpoint de citação — com as falhas nomeadas primeiro e cada razão medida, não suposta. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> registros completos", "<b>1</b> muro medido", "<b>0</b> inalcançável para um navegador", "<b>0,75 s</b> por fonte"]},
        {"date": "3 de agosto de 2026", "href": "reading-list-to-bibliography/",
         "title": "Vinte links, dez citações: o que uma máquina termina e o que devolve",
         "text": "Uma lista de leitura transformada em bibliografia, de ponta a ponta. Editoras científicas entregam registros, com paywall ou abertas; portais de estatística, câmaras de comércio e jornais não entregam nenhum — e só uma recusa em vinte foi defesa contra bots.",
         "figures": ["<b>10/20</b> registros completos", "<b>1</b> defesa contra bots", "<b>5</b> páginas sem nada a declarar", "<b>0,4 s</b> por fonte"]},
        {"date": "3 de agosto de 2026", "href": "citation-triage/",
         "title": "Um agente consegue citar oito de doze fontes — a parte útil é saber quais quatro não consegue",
         "text": "Uma lista de leitura mista por um endpoint de citação: registros completos com RIS para dois terços, e o terço restante nomeado com precisão suficiente para buscar à mão.",
         "figures": ["<b>8/12</b> feitas pelo agente", "<b>1,09 s</b> por fonte", "<b>4</b> nomeadas, não adivinhadas"]},
        {"date": "3 de agosto de 2026", "href": "citation-by-platform/",
         "title": "Onde os dados de citação realmente vivem: 18 plataformas acadêmicas medidas",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex e mais treze, cada uma verificada pelo que declara sobre as próprias obras — com cada título devolvido conferido contra a Crossref.",
         "figures": ["<b>11/18</b> devolveram dados", "<b>10</b> com autores e ano", "<b>8</b> bateram com a Crossref"]},
        {"date": "2 de agosto de 2026", "href": "citation-extraction/",
         "title": "Medido contra o Citoid em amostras aleatórias: mesma cobertura, nada inventado",
         "text": "O serviço da Wikimedia construído sobre os tradutores do Zotero é o parâmetro. Em 18 obras sorteadas ao acaso: cobertura igual, e nenhum bloqueio relatado como sucesso.",
         "figures": ["<b>13/13</b> campos completos", "<b>0</b> falsos relatórios de bloqueio", "<b>0,35 s</b> de mediana"]},
        {"date": "2 de agosto de 2026", "href": "android-capture-extensions/",
         "title": "Quais extensões de salvar página realmente rodam no Firefox para Android?",
         "text": "248 extensões verificadas contra a API de complementos. O Chrome para Android não consegue instalar nenhuma — então a pergunta só surge no Firefox. Inclui a correção da nossa própria página na loja.",
         "figures": ["<b>60</b> declaram Android", "<b>85.724</b> usuários na maior", "<b>0</b> testadas num aparelho"]},
        {"date": "2 de agosto de 2026", "href": "web-citations-that-vanish/",
         "title": "Citações da web que desaparecem: o que acontece com uma fonte depois de citada",
         "text": "Por que a data de consulta está em toda bibliografia, o que a pesquisa sobre link rot e content drift mostra, e 150 fontes citadas verificadas quanto à existência de uma cópia em algum lugar. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19,3 %</b> desaparecidas", "<b>603 dias</b> de idade mediana do arquivo", "<b>2,0 %</b> irrecuperáveis"]},
        {"date": "1 de agosto de 2026", "href": "print-to-pdf-vs-screenshot/",
         "title": "Imprimir em PDF ou capturar a tela? A mesma página medida dos dois jeitos",
         "text": "O Firefox já exporta PDFs de graça. O mesmo artigo pelas duas vias — incluindo onde a impressão vence.",
         "figures": ["<b>1 : 26</b> páginas", "<b>9</b> quebras cortam uma frase", "captura: <b>91,5 %</b> de recall"]},
        {"date": "1 de agosto de 2026", "href": "webpage-to-pdf-for-ocr/",
         "title": "Página da web em PDF para OCR: quanto texto realmente sobrevive?",
         "text": "Um PDF de captura pelo Tesseract, comparado com o texto de origem, mais o limiar de resolução em que o reconhecimento colapsa.",
         "figures": ["<b>92,6 %</b> recuperado", "<b>8/8</b> valores críticos", "<b>72 dpi</b> colapso"]},
        {"date": "1 de agosto de 2026", "href": "pdf-extension-permissions/",
         "title": "Sua extensão de PDF envia a página?",
         "text": "O que oito extensões de captura declaram em seus manifestos, como verificar em 30 segundos, e por que conversores no lado do servidor não alcançam um login.",
         "figures": ["<b>8</b> extensões", "dados brutos publicados"]},
        {"date": "1 de agosto de 2026", "href": "extension-permissions-risk/",
         "title": "Uma extensão só é tão perigosa quanto suas permissões permitem",
         "text": "Um ano depois do alerta da Mozilla sobre contas de desenvolvedor roubadas: o escopo das permissões como raio de dano, não como sinal de confiança.",
         "figures": ["tabela do pior caso", "checklist de avaliação"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Sobre &amp; transparência</a> · Correções: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues no GitHub</a> · <a href="../disclaimer/">Aviso legal</a>',
}

TEXTE["measurements"]["ru"] = {
    "h1": "Измерения",
    "lead": "Каждое — с командами для его повторения, сырыми данными за ним и контрольным прогоном — потому что метод, который не отказывает там, где должен, не измеряет ничего.",
    "items": [
        {"date": "3 августа 2026 г.", "href": "install-an-extension-without-a-click/",
         "title": "Установка расширения браузера без единого щелчка — и удаление обратно",
         "text": "Четыре пути, в обе стороны, на обычной учётной записи. Собственный канал Marionette в Firefox устанавливает и удаляет подписанную магазинную сборку без окна — а две команды вместе занимают четверть секунды; цена — запуск браузера, а не работа. Путь со щелчком сообщил об успехе на каждом шаге и не установил ничего.",
         "figures": ["<b>4,1 с</b> туда-обратно", "<b>0,24 с</b> сами команды", "<b>0</b> событий ввода", "<b>179 с</b> на путь со щелчком, который не удался"]},
        {"date": "3 августа 2026 г.", "href": "de-plattformen/",
         "title": "Немецкоязычные научные платформы измерены: четыре прочитаны, семь возвращены",
         "text": "SSOAR, PsychArchives, peDOCS, OPUS, Национальная библиотека, Springer, Nomos, beck-online, openJur, Statistik Austria и Destatis через конечную точку цитирования — с неудачами названными первыми и каждой причиной измеренной, а не предположенной. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>4/11</b> полных записей", "<b>1</b> измеренная стена", "<b>0</b> недостижимых для браузера", "<b>0,75 с</b> на источник"]},
        {"date": "3 августа 2026 г.", "href": "reading-list-to-bibliography/",
         "title": "Двадцать ссылок, десять цитат: что машина доводит до конца, а что возвращает",
         "text": "Список чтения в библиографию, от начала до конца. Научные издательства дают записи, за пейволом или открыто; статистические порталы, торговые палаты и газеты не дают никаких — и лишь один отказ из двадцати был защитой от ботов.",
         "figures": ["<b>10/20</b> полных записей", "<b>1</b> защита от ботов", "<b>5</b> страниц без единого заявления", "<b>0,4 с</b> на источник"]},
        {"date": "3 августа 2026 г.", "href": "citation-triage/",
         "title": "Агент может процитировать восемь из двенадцати источников — полезно знать, какие четыре он не может",
         "text": "Смешанный список чтения через конечную точку цитирования: полные записи с RIS для двух третей, а оставшаяся треть названа достаточно точно, чтобы забрать её вручную.",
         "figures": ["<b>8/12</b> сделано агентом", "<b>1,09 с</b> на источник", "<b>4</b> названы, а не угаданы"]},
        {"date": "3 августа 2026 г.", "href": "citation-by-platform/",
         "title": "Где на самом деле живут данные цитирования: измерено 18 научных платформ",
         "text": "PubMed, arXiv, Zenodo, SSRN, EUR-Lex и ещё тринадцать, каждая проверена на то, что она заявляет о собственных произведениях, — с каждым возвращённым заглавием, сверенным с Crossref.",
         "figures": ["<b>11/18</b> вернули данные", "<b>10</b> с авторами и годом", "<b>8</b> совпали с Crossref"]},
        {"date": "2 августа 2026 г.", "href": "citation-extraction/",
         "title": "Измерено против Citoid на случайных выборках: то же покрытие, ничего выдуманного",
         "text": "Эталон — сервис Wikimedia, построенный на трансляторах Zotero. На 18 случайно извлечённых произведениях: одинаковое покрытие, и ни одной блокировки, доложенной как успех.",
         "figures": ["<b>13/13</b> полей заполнены", "<b>0</b> ложных сообщений о блокировке", "<b>0,35 с</b> медиана"]},
        {"date": "2 августа 2026 г.", "href": "android-capture-extensions/",
         "title": "Какие расширения для сохранения страниц реально работают на Firefox для Android?",
         "text": "248 расширений, проверенных через API дополнений. Chrome для Android не может установить ни одного — поэтому вопрос встаёт только на Firefox. Включая исправление нашей собственной карточки в магазине.",
         "figures": ["<b>60</b> заявляют Android", "<b>85 724</b> пользователей у крупнейшего", "<b>0</b> проверено на устройстве"]},
        {"date": "2 августа 2026 г.", "href": "web-citations-that-vanish/",
         "title": "Веб-цитаты, которые исчезают: что происходит с источником после цитирования",
         "text": "Почему дата обращения есть в каждой библиографии, что показывают исследования о гниении ссылок и дрейфе содержимого, и 150 процитированных источников, проверенных, существует ли где-нибудь копия. Deutsche Fassung auf derselben Seite.",
         "figures": ["<b>19,3 %</b> исчезли", "<b>603 дня</b> медианный возраст архива", "<b>2,0 %</b> невосстановимы"]},
        {"date": "1 августа 2026 г.", "href": "print-to-pdf-vs-screenshot/",
         "title": "Печатать в PDF или захватывать экран? Одна и та же страница, измеренная двумя способами",
         "text": "Firefox уже экспортирует PDF бесплатно. Одна и та же статья обоими путями — включая то, где печать выигрывает.",
         "figures": ["<b>1 : 26</b> страниц", "<b>9</b> разрывов режут предложение", "захват: <b>91,5 %</b> полноты"]},
        {"date": "1 августа 2026 г.", "href": "webpage-to-pdf-for-ocr/",
         "title": "Веб-страница в PDF для OCR: сколько текста реально выживает?",
         "text": "PDF скриншота через Tesseract, сравнение с исходным текстом, плюс порог разрешения, на котором распознавание рушится.",
         "figures": ["<b>92,6 %</b> восстановлено", "<b>8/8</b> критических значений", "<b>72 dpi</b> обвал"]},
        {"date": "1 августа 2026 г.", "href": "pdf-extension-permissions/",
         "title": "Выгружает ли ваше PDF-расширение страницу?",
         "text": "Что декларируют восемь расширений для захвата в своих манифестах, как проверить это за 30 секунд, и почему серверные конвертеры не достают до логина.",
         "figures": ["<b>8</b> расширений", "сырые данные опубликованы"]},
        {"date": "1 августа 2026 г.", "href": "extension-permissions-risk/",
         "title": "Расширение опасно ровно настолько, насколько позволяют его разрешения",
         "text": "Год спустя после предупреждения Mozilla об украденных учётках разработчиков: объём разрешений как радиус поражения, а не как сигнал доверия.",
         "figures": ["таблица наихудшего случая", "контрольный список оценки"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">О сайте и раскрытие</a> · Исправления: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues на GitHub</a> · <a href="../disclaimer/">Отказ от ответственности</a>',
}

TEXTE["measurements"]["zh-CN"] = {
    "h1": "测量",
    "lead": "每一项都附有复现它的命令、背后的原始数据和对照运行——因为不会在应当失败之处失败的方法,什么也测不到。",
    "items": [
        {"date": "2026年8月3日", "href": "install-an-extension-without-a-click/",
         "title": "无需点击即可安装浏览器扩展,并将其移除",
         "text": "四条路径,双向,在普通用户账户上。Firefox 自带的 Marionette 通道可无窗口安装和卸载商店签名版本——而两条命令合计只需四分之一秒,成本在启动浏览器,而非工作。点击路径每一步都报告成功,却什么都没装上。",
         "figures": ["往返 <b>4.1 秒</b>", "命令本身 <b>0.24 秒</b>", "输入事件 <b>0</b>", "失败的点击路径 <b>179 秒</b>"]},
        {"date": "2026年8月3日", "href": "de-plattformen/",
         "title": "德语学术平台实测:四家可读,七家被退回",
         "text": "SSOAR、PsychArchives、peDOCS、OPUS、国家图书馆、Springer、Nomos、beck-online、openJur、Statistik Austria 和 Destatis 经由引用端点——失败先列,每个原因都经过测量而非猜测。Deutsche Fassung auf derselben Seite.",
         "figures": ["完整记录 <b>4/11</b>", "测得的墙 <b>1</b>", "浏览器无法到达 <b>0</b>", "每个来源 <b>0.75 秒</b>"]},
        {"date": "2026年8月3日", "href": "reading-list-to-bibliography/",
         "title": "二十个链接,十条引用:机器完成了什么,交还了什么",
         "text": "把一份阅读清单从头到尾变成参考文献。学术出版社无论付费墙还是开放都会给出记录;统计门户、商会和报纸一条也不给——而二十次拒绝中只有一个是反机器人防御。",
         "figures": ["完整记录 <b>10/20</b>", "反机器人防御 <b>1</b>", "无任何可声明内容的页面 <b>5</b>", "每个来源 <b>0.4 秒</b>"]},
        {"date": "2026年8月3日", "href": "citation-triage/",
         "title": "代理能引用 12 个来源中的 8 个——有用的部分是知道哪 4 个不行",
         "text": "把一份混合阅读清单送入引用端点:三分之二得到带 RIS 的完整记录,其余三分之一被足够精确地命名,可以手动获取。",
         "figures": ["代理完成 <b>8/12</b>", "每个来源 <b>1.09 秒</b>", "被指名而非猜测 <b>4</b>"]},
        {"date": "2026年8月3日", "href": "citation-by-platform/",
         "title": "引用数据究竟在哪里:18 个学术平台实测",
         "text": "PubMed、arXiv、Zenodo、SSRN、EUR-Lex 以及另外十三家,逐一检查它们对自身著作声明了什么——每个返回的标题都与 Crossref 核对。",
         "figures": ["返回数据 <b>11/18</b>", "含作者和年份 <b>10</b>", "与 Crossref 相符 <b>8</b>"]},
        {"date": "2026年8月2日", "href": "citation-extraction/",
         "title": "在随机样本上与 Citoid 对比测量:相同覆盖率,零编造",
         "text": "基于 Zotero 翻译器构建的维基媒体服务是标尺。随机抽取 18 部著作:覆盖率相同,没有一次拦截被报为成功。",
         "figures": ["字段完整 <b>13/13</b>", "错误的拦截报告 <b>0</b>", "中位数 <b>0.35 秒</b>"]},
        {"date": "2026年8月2日", "href": "android-capture-extensions/",
         "title": "哪些页面保存扩展真正能在 Android 版 Firefox 上运行?",
         "text": "对照扩展 API 检查了 248 款扩展。Android 版 Chrome 一款也装不了——所以这个问题只在 Firefox 上存在。包括对我们自己商店页面的更正。",
         "figures": ["声明支持 Android <b>60</b>", "最大的一款用户 <b>85,724</b>", "在设备上实测 <b>0</b>"]},
        {"date": "2026年8月2日", "href": "web-citations-that-vanish/",
         "title": "会消失的网络引用:引用之后,来源会发生什么",
         "text": "为什么每个参考文献列表都需要获取日期,关于链接腐烂和内容漂移的研究显示了什么,以及检查 150 个被引来源是否在某处存在副本。Deutsche Fassung auf derselben Seite.",
         "figures": ["已消失 <b>19.3%</b>", "存档年龄中位数 <b>603 天</b>", "无法恢复 <b>2.0%</b>"]},
        {"date": "2026年8月1日", "href": "print-to-pdf-vs-screenshot/",
         "title": "打印为 PDF 还是截屏?同一页面两种方式实测",
         "text": "Firefox 已经可以免费导出 PDF。同一篇文章走两条路径——包括打印胜出的地方。",
         "figures": ["页数 <b>1 : 26</b>", "<b>9</b> 处分页截断句子", "捕获:召回率 <b>91.5%</b>"]},
        {"date": "2026年8月1日", "href": "webpage-to-pdf-for-ocr/",
         "title": "网页转 PDF 用于 OCR:究竟有多少文本存活?",
         "text": "把截图 PDF 送入 Tesseract,与源文本对比,外加识别崩溃的分辨率阈值。",
         "figures": ["恢复 <b>92.6%</b>", "关键值 <b>8/8</b>", "崩溃 <b>72 dpi</b>"]},
        {"date": "2026年8月1日", "href": "pdf-extension-permissions/",
         "title": "你的 PDF 扩展会上传页面吗?",
         "text": "八款捕获扩展在清单中声明了什么、如何在 30 秒内验证,以及为什么服务器端转换器够不到登录。",
         "figures": ["扩展 <b>8</b> 款", "原始数据已公开"]},
        {"date": "2026年8月1日", "href": "extension-permissions-risk/",
         "title": "扩展的危险程度只取决于其权限允许的范围",
         "text": "在 Mozilla 就开发者账户被钓鱼发出警告一年后:权限范围是伤害半径,而不是信任信号。",
         "figures": ["最坏情况表", "评估清单"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">关于与披露</a> · 更正: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">免责声明</a>',
}
