#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Die About-/Offenlegungsseite in neun Sprachen — getrennt vom Bauen.

Muster wie texte_for_agents.py: ENGLISCH ist die Ausgangsfassung, Rendering
ueber build_about.py. EN und DE sind WOERTLICH aus der bisherigen Seite
uebernommen (rechtlich gepruefter Stand), die uebrigen sieben Sprachen sind
konservative Uebersetzungen: keine neuen Tatsachenbehauptungen, keine
Werbesprache. Links und E-Mail-Adressen bleiben in allen Sprachen identisch.

Fliesstexte stehen absichtlich in einer logischen Zeile (keine Umbrueche),
damit Satz-Kennsaeze im Browsertest per innerText gefunden werden.

Aenderungen am Inhalt HIER, danach `python3 build_about.py`.
"""

URL = "https://provinglab.dev/about/"
SPRACHEN = ["en", "de", "es", "fr", "it", "ja", "pt-BR", "ru", "zh-CN"]
BASIS = "en"

TEXTE = {}

# --------------------------------------------------------------- English ----
TEXTE["en"] = {
    "h1": "About &amp; disclosure",
    "lead": "A private, non-commercial publication. Who runs it, how the figures are produced, and what it deliberately does not offer.",
    "what_h2": "What this site is",
    "what_p": "A personal notebook, published openly. It contains measurements on browser tools and reports from building software. It exists because the results are more useful public than private — not as a business.",
    "box_h3": "Non-commercial, and structurally so",
    "box_items": [
        "Nothing is sold here, and nothing is offered for sale.",
        "No advertising, no sponsored content, no affiliate links, no tracking, no newsletter.",
        "The software discussed is free of charge and published under the MIT licence.",
        "No payment is accepted in any form, and no service is offered against payment.",
        "No contract comes into existence through use of this site.",
    ],
    "who_h2": "Who runs it",
    "op_dt": "Operator",
    "op_dd": "Published under the pseudonym <strong>Silence</strong> — the same handle used for the software on addons.mozilla.org and on GitHub as <code>Bubu89</code>.",
    "contact_dt": "Contact",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> Messages are read and answered. For anything concerning the published content, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">an issue in the repository</a> is faster and leaves a public record.',
    "legal_dt": "Legal contact",
    "legal_dd": "For matters requiring the operator's full identity — legal notices, formal requests, right-of-reply claims — write to the address above. Identity and postal details are disclosed to a legitimate requester without delay.",
    "disco_h2": "Disclosure",
    "disco_p1": 'This site is run by the developer of <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, which appears in several of the published measurements. That connection is stated in every article where it is relevant, and the software sits openly under <code>/tools/</code> rather than behind neutral framing.',
    "disco_p2": "No product mentioned here has sponsored, reviewed or approved its coverage. Nobody pays for placement, because there is no placement to buy.",
    "fig_h2": "How the figures are produced",
    "fig_items": [
        "Every figure carries the date it was obtained and the tool that produced it.",
        "Raw data is published alongside, so numbers can be checked rather than believed.",
        "Each method runs against a reference case first — a method that does not fail where it should is not measuring anything.",
        "Statements about third-party products come exclusively from publicly declared data: manifests, listing descriptions, public APIs, and the providers' own words. Retrieval date always given.",
        "Nothing has been decompiled. No claim is made about any provider's intentions or about data actually transmitted — only about what is publicly declared.",
    ],
    "warn_h3": "What this site does not provide",
    "warn_p1": "Nothing here is legal, security, tax or financial advice. Measurements are single runs on specific inputs on a specific day — reports, not studies. Software changes continuously; a figure from August 2026 may be wrong three months later. Verify against the live source before relying on anything.",
    "warn_p2": "In particular: a PDF produced by screen capture is <strong>not a qualified electronic document</strong>. It carries no qualified signature, no trusted timestamp and no chain of custody. It records what a browser displayed at a moment in time — suitable for your own records, not equivalent to notarised or court-grade preservation of evidence.",
    "warn_p3": "No liability is accepted for decisions taken on the basis of content published here, to the extent permitted by law. Statutory liability for intent and gross negligence remains unaffected.",
    "warn_p4": "Articles on this site occasionally touch on questions with a legal dimension — permissions, licences, copyright, the evidentiary weight of a record. None of it is legal advice. For a specific situation, qualified advice is the right route.",
    "links_h2": "External links",
    "links_p": "Links point to content operated by others. Their content is their responsibility; at the time of linking no infringement was apparent. If a linked page later becomes unlawful, a note to the contact above removes the link.",
    "corr_h2": "Corrections",
    "corr_p": 'If something here is wrong, say so and it gets corrected — in the article itself, not as an appended footnote. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Open an issue</a> or use the contact address. Substantive corrections are noted with their date.',
    "reuse_h2": "Reuse",
    "reuse_p": 'Text and data on this site are published under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — reuse is welcome with attribution and a link. The software is a different matter and carries the <a href="https://opensource.org/licenses/MIT">MIT licence</a>: a software licence covers code, not prose, so the two are stated separately rather than lumped together.',
}

# --------------------------------------------------------------- Deutsch ----
TEXTE["de"] = {
    "h1": "Über &amp; Offenlegung",
    "lead": "Eine private, nicht-kommerzielle Veröffentlichung. Wer sie betreibt, wie die Zahlen entstehen und was sie bewusst nicht anbietet.",
    "what_h2": "Was diese Seite ist",
    "what_p": "Ein persönliches Notizbuch, offen veröffentlicht. Es enthält Messungen zu Browser-Werkzeugen und Berichte aus der Softwareentwicklung. Es existiert, weil die Ergebnisse öffentlich mehr nützen als privat — nicht als Geschäft.",
    "box_h3": "Nicht-kommerziell, und zwar strukturell",
    "box_items": [
        "Hier wird nichts verkauft und nichts zum Verkauf angeboten.",
        "Keine Werbung, keine bezahlten Beiträge, keine Affiliate-Links, kein Tracking, kein Newsletter.",
        "Die besprochene Software ist kostenlos und steht unter der MIT-Lizenz.",
        "Es werden keinerlei Zahlungen entgegengenommen und keine Leistungen gegen Entgelt angeboten.",
        "Durch die Nutzung dieser Seite kommt kein Vertrag zustande.",
    ],
    "who_h2": "Wer sie betreibt",
    "op_dt": "Betreiber",
    "op_dd": "Veröffentlichung unter dem Pseudonym <strong>Silence</strong> — dasselbe Kürzel wie für die Software auf addons.mozilla.org und auf GitHub als <code>Bubu89</code>.",
    "contact_dt": "Kontakt",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> Nachrichten werden gelesen und beantwortet. Für alles, was die veröffentlichten Inhalte betrifft, ist <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">ein Issue im Repository</a> schneller und öffentlich nachvollziehbar.',
    "legal_dt": "Rechtlicher Kontakt",
    "legal_dd": "Für Angelegenheiten, die die vollständige Identität des Betreibers erfordern — rechtliche Hinweise, förmliche Aufforderungen, Gegendarstellungsbegehren — genügt eine Nachricht an die obige Adresse. Identität und Anschrift werden einem berechtigten Anfragenden unverzüglich mitgeteilt.",
    "disco_h2": "Offenlegung",
    "disco_p1": 'Diese Seite wird vom Entwickler der Erweiterung <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a> betrieben, die in mehreren der veröffentlichten Messungen vorkommt. Dieser Zusammenhang wird in jedem Artikel genannt, in dem er eine Rolle spielt, und die Software liegt offen unter <code>/tools/</code> statt hinter neutraler Aufmachung.',
    "disco_p2": "Kein hier erwähntes Produkt hat seine Erwähnung gesponsert, gegengelesen oder freigegeben. Niemand zahlt für eine Platzierung, weil es keine zu kaufen gibt.",
    "fig_h2": "Wie die Zahlen entstehen",
    "fig_items": [
        "Jede Zahl trägt das Datum der Erhebung und das verwendete Werkzeug.",
        "Die Rohdaten werden mitveröffentlicht — Zahlen sollen prüfbar sein, nicht geglaubt werden müssen.",
        "Jede Methode läuft zuerst gegen einen Referenzfall: Ein Verfahren, das dort nicht durchfällt, wo es durchfallen muss, misst nichts.",
        "Aussagen über fremde Produkte stammen ausschließlich aus öffentlich deklarierten Daten: Manifeste, Store-Beschreibungen, offene Schnittstellen und die eigenen Angaben der Anbieter. Das Abrufdatum wird stets genannt.",
        "Es wurde nichts dekompiliert. Es wird keine Aussage über Absichten eines Anbieters oder über tatsächlich übertragene Daten getroffen — nur darüber, was öffentlich deklariert ist.",
    ],
    "warn_h3": "Was diese Seite ausdrücklich nicht leistet",
    "warn_p1": "Nichts hier ist Rechts-, Sicherheits-, Steuer- oder Finanzberatung. Messungen sind Einzelläufe mit bestimmten Eingaben an einem bestimmten Tag — Berichte, keine Studien. Software ändert sich laufend; eine Zahl von August 2026 kann drei Monate später falsch sein. Vor jeder Verwendung gegen die Live-Quelle prüfen.",
    "warn_p2": "Insbesondere: Ein durch Bildschirmaufnahme erzeugtes PDF ist <strong>kein qualifiziertes elektronisches Dokument</strong>. Es trägt keine qualifizierte Signatur, keinen vertrauenswürdigen Zeitstempel und keine lückenlose Nachweiskette. Es hält fest, was ein Browser zu einem Zeitpunkt angezeigt hat — geeignet für die eigenen Unterlagen, nicht gleichzusetzen mit notarieller oder gerichtsfester Beweissicherung.",
    "warn_p3": "Für Entscheidungen, die auf hier veröffentlichten Inhalten beruhen, wird im gesetzlich zulässigen Rahmen keine Haftung übernommen. Die gesetzliche Haftung für Vorsatz und grobe Fahrlässigkeit bleibt unberührt.",
    "warn_p4": "Beiträge dieser Seite behandeln gelegentlich Fragen mit rechtlichem Bezug — Berechtigungen, Lizenzen, Urheberrecht, Beweiswert von Aufzeichnungen. Nichts davon ist Rechtsberatung. Für den konkreten Fall gehört eine fachkundige Beratung eingeholt.",
    "links_h2": "Externe Verweise",
    "links_p": "Verweise führen zu Inhalten, die andere betreiben. Für deren Inhalte sind ausschließlich diese verantwortlich; zum Zeitpunkt der Verlinkung war kein Rechtsverstoß erkennbar. Wird eine verlinkte Seite später rechtswidrig, genügt ein Hinweis an die obige Adresse und der Verweis wird entfernt.",
    "corr_h2": "Korrekturen",
    "corr_p": 'Wenn hier etwas falsch ist, sagen Sie es — es wird korrigiert, und zwar im Artikel selbst, nicht als angehängte Fußnote. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Issue eröffnen</a> oder die Kontaktadresse nutzen. Inhaltliche Korrekturen werden mit Datum vermerkt.',
    "reuse_h2": "Weiterverwendung",
    "reuse_p": 'Texte und Daten dieser Seite stehen unter <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — Weiterverwendung ist erwünscht, mit Quellenangabe und Link. Die Software ist etwas anderes und trägt die <a href="https://opensource.org/licenses/MIT">MIT-Lizenz</a>: Eine Softwarelizenz deckt Code, keinen Fließtext, deshalb stehen beide getrennt statt in einem Satz.',
}

# --------------------------------------------------------------- Español ----
TEXTE["es"] = {
    "h1": "Acerca de y divulgación",
    "lead": "Una publicación privada y no comercial. Quién la opera, cómo se producen las cifras y qué no ofrece deliberadamente.",
    "what_h2": "Qué es este sitio",
    "what_p": "Un cuaderno personal, publicado abiertamente. Contiene mediciones sobre herramientas de navegador e informes del desarrollo de software. Existe porque los resultados son más útiles públicos que privados, no como un negocio.",
    "box_h3": "No comercial, y estructuralmente así",
    "box_items": [
        "Aquí no se vende nada ni se ofrece nada a la venta.",
        "Sin publicidad, sin contenido patrocinado, sin enlaces de afiliado, sin seguimiento, sin boletín.",
        "El software comentado es gratuito y se publica bajo la licencia MIT.",
        "No se acepta ningún pago de ninguna forma y no se ofrece ningún servicio a cambio de una contraprestación.",
        "El uso de este sitio no da lugar a ningún contrato.",
    ],
    "who_h2": "Quién lo opera",
    "op_dt": "Operador",
    "op_dd": "Publicado bajo el seudónimo <strong>Silence</strong> — el mismo identificador usado para el software en addons.mozilla.org y en GitHub como <code>Bubu89</code>.",
    "contact_dt": "Contacto",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> Los mensajes se leen y se responden. Para todo lo relacionado con el contenido publicado, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">una incidencia en el repositorio</a> es más rápida y deja constancia pública.',
    "legal_dt": "Contacto legal",
    "legal_dd": "Para asuntos que requieran la identidad completa del operador —avisos legales, solicitudes formales, peticiones de derecho de réplica— escriba a la dirección indicada arriba. La identidad y la dirección postal se comunican sin demora a quien tenga un interés legítimo.",
    "disco_h2": "Divulgación",
    "disco_p1": 'Este sitio es operado por el desarrollador de <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, que aparece en varias de las mediciones publicadas. Esta relación se indica en cada artículo en el que es relevante, y el software está a la vista bajo <code>/tools/</code> en lugar de detrás de una presentación neutral.',
    "disco_p2": "Ningún producto mencionado aquí ha patrocinado, revisado o aprobado su cobertura. Nadie paga por una ubicación, porque no hay ninguna ubicación que comprar.",
    "fig_h2": "Cómo se producen las cifras",
    "fig_items": [
        "Cada cifra lleva la fecha en que se obtuvo y la herramienta que la produjo.",
        "Los datos brutos se publican junto a ellas, de modo que las cifras puedan comprobarse en lugar de creerse.",
        "Cada método se ejecuta primero contra un caso de referencia: un método que no falla donde debería fallar no está midiendo nada.",
        "Las afirmaciones sobre productos de terceros proceden exclusivamente de datos declarados públicamente: manifiestos, descripciones de las tiendas, API públicas y las propias declaraciones de los proveedores. Siempre se indica la fecha de consulta.",
        "No se ha descompilado nada. No se hace ninguna afirmación sobre las intenciones de ningún proveedor ni sobre los datos realmente transmitidos; solo sobre lo que está declarado públicamente.",
    ],
    "warn_h3": "Lo que este sitio no proporciona",
    "warn_p1": "Nada de lo aquí publicado es asesoramiento jurídico, de seguridad, fiscal o financiero. Las mediciones son ejecuciones únicas con entradas concretas en un día concreto: informes, no estudios. El software cambia continuamente; una cifra de agosto de 2026 puede ser errónea tres meses después. Compruebe la fuente en vivo antes de confiar en cualquier dato.",
    "warn_p2": "En particular: un PDF producido por captura de pantalla <strong>no es un documento electrónico cualificado</strong>. No lleva firma electrónica cualificada, ni sello de tiempo cualificado, ni cadena de custodia. Registra lo que un navegador mostró en un momento dado: adecuado para sus propios archivos, no equivalente a una conservación de pruebas notarial o con validez judicial.",
    "warn_p3": "No se acepta responsabilidad alguna por decisiones tomadas sobre la base de los contenidos publicados aquí, en la medida permitida por la ley. La responsabilidad legal por dolo y negligencia grave no se ve afectada.",
    "warn_p4": "Los artículos de este sitio abordan ocasionalmente cuestiones con dimensión jurídica: permisos, licencias, derechos de autor, el valor probatorio de un registro. Nada de ello constituye asesoramiento jurídico. Para una situación concreta, el camino adecuado es el asesoramiento cualificado.",
    "links_h2": "Enlaces externos",
    "links_p": "Los enlaces apuntan a contenidos operados por terceros. Su contenido es responsabilidad de estos; en el momento del enlace no se apreciaba ninguna infracción. Si una página enlazada se vuelve ilegal más adelante, un aviso a la dirección de contacto indicada arriba elimina el enlace.",
    "corr_h2": "Correcciones",
    "corr_p": 'Si algo aquí es incorrecto, dígalo y se corregirá: en el propio artículo, no como nota al pie añadida. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Abra una incidencia</a> o utilice la dirección de contacto. Las correcciones sustantivas se anotan con su fecha.',
    "reuse_h2": "Reutilización",
    "reuse_p": 'Los textos y datos de este sitio se publican bajo <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>: la reutilización es bienvenida con atribución y un enlace. El software es un asunto distinto y lleva la <a href="https://opensource.org/licenses/MIT">licencia MIT</a>: una licencia de software cubre código, no prosa, por lo que ambas se indican por separado en lugar de mezclarse.',
}

# --------------------------------------------------------------- Français ---
TEXTE["fr"] = {
    "h1": "À propos et transparence",
    "lead": "Une publication privée et non commerciale. Qui l'exploite, comment les chiffres sont produits et ce qu'elle ne propose délibérément pas.",
    "what_h2": "Ce qu'est ce site",
    "what_p": "Un carnet personnel, publié ouvertement. Il contient des mesures sur des outils de navigateur et des comptes rendus de développement logiciel. Il existe parce que les résultats sont plus utiles publics que privés — pas comme une entreprise.",
    "box_h3": "Non commercial, et structurellement",
    "box_items": [
        "Rien n'est vendu ici, et rien n'est proposé à la vente.",
        "Pas de publicité, pas de contenu sponsorisé, pas de liens d'affiliation, pas de suivi, pas de lettre d'information.",
        "Le logiciel présenté est gratuit et publié sous licence MIT.",
        "Aucun paiement n'est accepté sous quelque forme que ce soit, et aucun service n'est proposé contre rémunération.",
        "L'utilisation de ce site ne fait naître aucun contrat.",
    ],
    "who_h2": "Qui l'exploite",
    "op_dt": "Exploitant",
    "op_dd": "Publié sous le pseudonyme <strong>Silence</strong> — le même identifiant que celui utilisé pour le logiciel sur addons.mozilla.org et sur GitHub sous <code>Bubu89</code>.",
    "contact_dt": "Contact",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> Les messages sont lus et reçoivent une réponse. Pour tout ce qui concerne les contenus publiés, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">un ticket dans le dépôt</a> est plus rapide et laisse une trace publique.',
    "legal_dt": "Contact juridique",
    "legal_dd": "Pour les questions exigeant l'identité complète de l'exploitant — mentions légales, demandes formelles, demandes de droit de réponse — écrivez à l'adresse ci-dessus. L'identité et l'adresse postale sont communiquées sans délai à tout demandeur légitime.",
    "disco_h2": "Transparence",
    "disco_p1": 'Ce site est exploité par le développeur de <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, qui apparaît dans plusieurs des mesures publiées. Ce lien est indiqué dans chaque article où il est pertinent, et le logiciel est visible sous <code>/tools/</code> plutôt que derrière une présentation neutre.',
    "disco_p2": "Aucun produit mentionné ici n'a sponsorisé, relu ou approuvé sa couverture. Personne ne paie pour un emplacement, car il n'y a aucun emplacement à acheter.",
    "fig_h2": "Comment les chiffres sont produits",
    "fig_items": [
        "Chaque chiffre porte la date de son obtention et l'outil qui l'a produit.",
        "Les données brutes sont publiées avec, afin que les chiffres puissent être vérifiés plutôt que crus.",
        "Chaque méthode est d'abord exécutée sur un cas de référence : une méthode qui n'échoue pas là où elle devrait échouer ne mesure rien.",
        "Les affirmations sur des produits tiers proviennent exclusivement de données publiquement déclarées : manifestes, descriptions des catalogues, API publiques et déclarations des fournisseurs eux-mêmes. La date de consultation est toujours indiquée.",
        "Rien n'a été décompilé. Aucune affirmation n'est faite sur les intentions d'un fournisseur ni sur les données réellement transmises — uniquement sur ce qui est publiquement déclaré.",
    ],
    "warn_h3": "Ce que ce site ne fournit pas",
    "warn_p1": "Rien ici ne constitue un conseil juridique, de sécurité, fiscal ou financier. Les mesures sont des exécutions uniques sur des entrées précises, un jour précis — des comptes rendus, pas des études. Les logiciels évoluent en permanence ; un chiffre d'août 2026 peut être faux trois mois plus tard. Vérifiez à la source avant de vous fier à quoi que ce soit.",
    "warn_p2": "En particulier : un PDF produit par capture d'écran n'est <strong>pas un document électronique qualifié</strong>. Il ne porte ni signature électronique qualifiée, ni horodatage qualifié, ni chaîne de conservation. Il consigne ce qu'un navigateur a affiché à un instant donné — adapté à vos propres archives, sans équivalence avec une conservation de preuves notariée ou de valeur judiciaire.",
    "warn_p3": "Aucune responsabilité n'est acceptée pour les décisions prises sur la base des contenus publiés ici, dans la mesure permise par la loi. La responsabilité légale en cas de dol et de négligence grave demeure inchangée.",
    "warn_p4": "Les articles de ce site abordent parfois des questions à dimension juridique — autorisations, licences, droit d'auteur, valeur probante d'un enregistrement. Rien de tout cela ne constitue un conseil juridique. Pour une situation précise, un conseil qualifié est la bonne voie.",
    "links_h2": "Liens externes",
    "links_p": "Les liens renvoient à des contenus exploités par des tiers. Leur contenu relève de leur responsabilité ; au moment de la création du lien, aucune infraction n'était apparente. Si une page liée devient ultérieurement illicite, un signalement à l'adresse de contact ci-dessus entraîne la suppression du lien.",
    "corr_h2": "Corrections",
    "corr_p": 'Si quelque chose ici est erroné, dites-le et ce sera corrigé — dans l\'article lui-même, pas en note de bas de page ajoutée. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Ouvrez un ticket</a> ou utilisez l\'adresse de contact. Les corrections de fond sont consignées avec leur date.',
    "reuse_h2": "Réutilisation",
    "reuse_p": 'Les textes et données de ce site sont publiés sous <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — la réutilisation est bienvenue avec attribution et un lien. Le logiciel est une autre affaire et relève de la <a href="https://opensource.org/licenses/MIT">licence MIT</a> : une licence de logiciel couvre le code, pas la prose ; les deux sont donc indiquées séparément plutôt que confondues.',
}

# --------------------------------------------------------------- Italiano ---
TEXTE["it"] = {
    "h1": "Informazioni e trasparenza",
    "lead": "Una pubblicazione privata e non commerciale. Chi la gestisce, come vengono prodotte le cifre e cosa deliberatamente non offre.",
    "what_h2": "Che cos'è questo sito",
    "what_p": "Un taccuino personale, pubblicato apertamente. Contiene misurazioni su strumenti per browser e resoconti dello sviluppo di software. Esiste perché i risultati sono più utili pubblici che privati, non come un'attività commerciale.",
    "box_h3": "Non commerciale, e strutturalmente tale",
    "box_items": [
        "Qui non si vende nulla e nulla è offerto in vendita.",
        "Niente pubblicità, niente contenuti sponsorizzati, niente link di affiliazione, niente tracciamento, niente newsletter.",
        "Il software presentato è gratuito e pubblicato con licenza MIT.",
        "Non si accetta alcun pagamento in alcuna forma e non si offre alcun servizio a pagamento.",
        "L'uso di questo sito non dà luogo ad alcun contratto.",
    ],
    "who_h2": "Chi lo gestisce",
    "op_dt": "Gestore",
    "op_dd": "Pubblicato sotto lo pseudonimo <strong>Silence</strong> — lo stesso identificativo usato per il software su addons.mozilla.org e su GitHub come <code>Bubu89</code>.",
    "contact_dt": "Contatto",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> I messaggi vengono letti e ricevono risposta. Per tutto ciò che riguarda i contenuti pubblicati, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">una segnalazione nel repository</a> è più veloce e lascia una traccia pubblica.',
    "legal_dt": "Contatto legale",
    "legal_dd": "Per questioni che richiedono l'identità completa del gestore — comunicazioni legali, richieste formali, istanze di diritto di replica — scrivere all'indirizzo sopra indicato. Identità e recapito postale vengono comunicati senza ritardo a chi ne abbia legittimo interesse.",
    "disco_h2": "Trasparenza",
    "disco_p1": 'Questo sito è gestito dallo sviluppatore di <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, che compare in diverse delle misurazioni pubblicate. Questo legame è dichiarato in ogni articolo in cui è rilevante, e il software è esposto apertamente sotto <code>/tools/</code> anziché dietro una presentazione neutrale.',
    "disco_p2": "Nessun prodotto qui menzionato ha sponsorizzato, revisionato o approvato la propria copertura. Nessuno paga per un posizionamento, perché non esiste alcun posizionamento da acquistare.",
    "fig_h2": "Come vengono prodotte le cifre",
    "fig_items": [
        "Ogni cifra riporta la data in cui è stata ottenuta e lo strumento che l'ha prodotta.",
        "I dati grezzi sono pubblicati insieme, così che le cifre possano essere verificate anziché credute.",
        "Ogni metodo viene eseguito prima su un caso di riferimento: un metodo che non fallisce dove dovrebbe fallire non sta misurando nulla.",
        "Le affermazioni su prodotti di terzi provengono esclusivamente da dati pubblicamente dichiarati: manifest, descrizioni degli store, API pubbliche e le dichiarazioni dei fornitori stessi. La data di consultazione è sempre indicata.",
        "Nulla è stato decompilato. Non si fa alcuna affermazione sulle intenzioni di alcun fornitore né sui dati effettivamente trasmessi, ma solo su ciò che è pubblicamente dichiarato.",
    ],
    "warn_h3": "Cosa questo sito non fornisce",
    "warn_p1": "Nulla di quanto qui pubblicato costituisce consulenza legale, di sicurezza, fiscale o finanziaria. Le misurazioni sono singole esecuzioni su input specifici in un giorno specifico: resoconti, non studi. Il software cambia continuamente; una cifra di agosto 2026 può essere errata tre mesi dopo. Verificare alla fonte prima di fare affidamento su qualsiasi dato.",
    "warn_p2": "In particolare: un PDF prodotto tramite cattura dello schermo <strong>non è un documento elettronico qualificato</strong>. Non reca firma elettronica qualificata, né marca temporale qualificata, né catena di custodia. Registra ciò che un browser ha mostrato in un dato momento: adatto ai propri archivi, non equivalente a una conservazione probatoria notarile o con valore giudiziario.",
    "warn_p3": "Non si assume alcuna responsabilità per decisioni prese sulla base dei contenuti qui pubblicati, nei limiti consentiti dalla legge. Resta impregiudicata la responsabilità prevista dalla legge per dolo e colpa grave.",
    "warn_p4": "Gli articoli di questo sito toccano occasionalmente questioni con una dimensione giuridica: autorizzazioni, licenze, diritto d'autore, valore probatorio di una registrazione. Nulla di tutto ciò costituisce consulenza legale. Per una situazione specifica, la via giusta è una consulenza qualificata.",
    "links_h2": "Collegamenti esterni",
    "links_p": "I collegamenti rimandano a contenuti gestiti da terzi. Del loro contenuto sono responsabili esclusivamente questi ultimi; al momento del collegamento non era ravvisabile alcuna violazione. Se una pagina collegata diventa successivamente illecita, una segnalazione all'indirizzo di contatto sopra indicato comporta la rimozione del collegamento.",
    "corr_h2": "Correzioni",
    "corr_p": 'Se qualcosa qui è sbagliato, segnalatelo e verrà corretto: nell\'articolo stesso, non come nota a piè di pagina aggiunta. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Aprite una segnalazione</a> o usate l\'indirizzo di contatto. Le correzioni sostanziali vengono annotate con la relativa data.',
    "reuse_h2": "Riutilizzo",
    "reuse_p": 'Testi e dati di questo sito sono pubblicati con licenza <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>: il riutilizzo è benvenuto con attribuzione e un collegamento. Il software è un discorso diverso e reca la <a href="https://opensource.org/licenses/MIT">licenza MIT</a>: una licenza software copre il codice, non la prosa, per questo le due sono indicate separatamente anziché insieme.',
}

# ------------------------------------------------------------------ 日本語 --
TEXTE["ja"] = {
    "h1": "このサイトについて・開示事項",
    "lead": "個人の非営利の出版物です。運営者は誰か、数値がどのように生成されるか、そして何を意図的に提供していないかを記しています。",
    "what_h2": "このサイトは何か",
    "what_p": "公開された個人のノートです。ブラウザツールに関する測定と、ソフトウェア開発からの報告を収録しています。結果は非公開よりも公開した方が有益だから存在するのであり、事業としてではありません。",
    "box_h3": "非営利であり、構造的にそうです",
    "box_items": [
        "ここでは何も販売されず、販売の申し出もありません。",
        "広告、スポンサー付きコンテンツ、アフィリエイトリンク、トラッキング、ニュースレターはありません。",
        "取り上げるソフトウェアは無償で、MITライセンスの下で公開されています。",
        "いかなる形態の支払いも受け付けず、対価と引き換えのサービスも提供しません。",
        "このサイトの利用によって契約が成立することはありません。",
    ],
    "who_h2": "運営者",
    "op_dt": "運営者",
    "op_dd": "<strong>Silence</strong> という仮名で公開しています — addons.mozilla.org のソフトウェアおよび GitHub 上の <code>Bubu89</code> と同じハンドル名です。",
    "contact_dt": "連絡先",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> メッセージはすべて読み、返信します。公開コンテンツに関することは、<a href="https://github.com/Bubu89/full-page-pdf-snap/issues">リポジトリでの Issue</a> の方が早く、公開の記録も残ります。',
    "legal_dt": "法的連絡先",
    "legal_dd": "運営者の完全な身元を必要とする事項（法的通知、正式な要請、反論権の申し立てなど）については、上記の連絡先にお書きください。正当な請求者には、身元と郵送先住所を遅滞なく開示します。",
    "disco_h2": "開示事項",
    "disco_p1": 'このサイトは、公開された測定のいくつかに登場する <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a> の開発者が運営しています。この関係は、関連するすべての記事で明記されており、ソフトウェアは中立的な体裁の背後ではなく <code>/tools/</code> の下に公開されています。',
    "disco_p2": "ここで言及される製品のいずれも、その掲載に対してスポンサー、査読、承認を行っていません。買える掲載枠が存在しないため、誰も掲載のために支払っていません。",
    "fig_h2": "数値の生成方法",
    "fig_items": [
        "すべての数値には、取得日と生成に使用したツールが記されています。",
        "生データも併せて公開しているため、数値は信じるのではなく検証できます。",
        "各手法はまず参照ケースに対して実行されます。失敗すべきところで失敗しない手法は、何も測定していません。",
        "第三者の製品に関する記述は、公開されている宣言データのみに由来します: マニフェスト、ストアの説明文、公開 API、そして提供者自身の言葉です。取得日は必ず記載しています。",
        "逆コンパイルは一切行っていません。提供者の意図や実際に送信されたデータについての主張は行わず、公開宣言されている内容のみについて述べています。",
    ],
    "warn_h3": "このサイトが提供しないもの",
    "warn_p1": "ここにあるものは、法的、セキュリティ、税務、金融のいずれの助言でもありません。測定は特定の日に特定の入力で行った単一の実行であり、研究ではなく報告です。ソフトウェアは絶えず変化します。2026年8月の数値は3か月後には誤りかもしれません。何かに依拠する前に、必ず最新の出所で確認してください。",
    "warn_p2": "特に: 画面キャプチャで生成された PDF は<strong>適格電子文書ではありません</strong>。適格電子署名、信任されたタイムスタンプ、証拠保全の連鎖のいずれも備えていません。ブラウザがある時点で表示した内容を記録するものであり、自分の記録用には適していますが、公証または裁判レベルの証拠保全と同等ではありません。",
    "warn_p3": "ここに公開された内容に基づいて行われた決定について、法律で認められる範囲で一切の責任を負いません。故意および重過失に対する法定責任は影響を受けません。",
    "warn_p4": "このサイトの記事は、許可、ライセンス、著作権、記録の証拠能力など、法的な側面を持つ問題に時折触れます。そのいずれも法的助言ではありません。具体的な状況については、資格のある専門家への相談が適切な方法です。",
    "links_h2": "外部リンク",
    "links_p": "リンクは他者が運営するコンテンツを指しています。その内容はリンク先の運営者の責任であり、リンク設定時点で違法な点は認められませんでした。リンク先のページが後に違法になった場合は、上記の連絡先への連絡によりリンクを削除します。",
    "corr_h2": "訂正",
    "corr_p": 'ここに誤りがあればお知らせください。追記の脚注としてではなく、記事そのものの中で訂正します。<a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Issue を開く</a>か、連絡先アドレスをご利用ください。内容に関わる訂正には日付を付記します。',
    "reuse_h2": "再利用",
    "reuse_p": 'このサイトのテキストとデータは <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> の下で公開されており、出典表示とリンク付きでの再利用を歓迎します。ソフトウェアは別の扱いで、<a href="https://opensource.org/licenses/MIT">MITライセンス</a>が適用されます。ソフトウェアライセンスは散文ではなくコードを対象とするため、両者をまとめずに分けて記しています。',
}

# ------------------------------------------------------------- Português ----
TEXTE["pt-BR"] = {
    "h1": "Sobre e divulgação",
    "lead": "Uma publicação privada e sem fins comerciais. Quem a opera, como os números são produzidos e o que ela deliberadamente não oferece.",
    "what_h2": "O que é este site",
    "what_p": "Um caderno pessoal, publicado abertamente. Contém medições sobre ferramentas de navegador e relatos do desenvolvimento de software. Existe porque os resultados são mais úteis públicos do que privados — não como um negócio.",
    "box_h3": "Não comercial, e estruturalmente assim",
    "box_items": [
        "Nada é vendido aqui, e nada é oferecido à venda.",
        "Sem publicidade, sem conteúdo patrocinado, sem links de afiliados, sem rastreamento, sem newsletter.",
        "O software discutido é gratuito e publicado sob a licença MIT.",
        "Nenhum pagamento é aceito sob qualquer forma, e nenhum serviço é oferecido mediante remuneração.",
        "Nenhum contrato se forma pelo uso deste site.",
    ],
    "who_h2": "Quem o opera",
    "op_dt": "Operador",
    "op_dd": "Publicado sob o pseudônimo <strong>Silence</strong> — o mesmo identificador usado para o software em addons.mozilla.org e no GitHub como <code>Bubu89</code>.",
    "contact_dt": "Contato",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> As mensagens são lidas e respondidas. Para tudo o que diz respeito ao conteúdo publicado, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">uma issue no repositório</a> é mais rápida e deixa registro público.',
    "legal_dt": "Contato jurídico",
    "legal_dd": "Para questões que exijam a identidade completa do operador — notificações legais, pedidos formais, solicitações de direito de resposta — escreva para o endereço acima. A identidade e o endereço postal são divulgados sem demora a um solicitante legítimo.",
    "disco_h2": "Divulgação",
    "disco_p1": 'Este site é operado pelo desenvolvedor do <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, que aparece em várias das medições publicadas. Essa relação é declarada em cada artigo em que é relevante, e o software está exposto abertamente em <code>/tools/</code>, em vez de por trás de uma apresentação neutra.',
    "disco_p2": "Nenhum produto mencionado aqui patrocinou, revisou ou aprovou sua cobertura. Ninguém paga por posicionamento, porque não existe posicionamento à venda.",
    "fig_h2": "Como os números são produzidos",
    "fig_items": [
        "Cada número carrega a data em que foi obtido e a ferramenta que o produziu.",
        "Os dados brutos são publicados junto, para que os números possam ser verificados, e não apenas acreditados.",
        "Cada método é executado primeiro contra um caso de referência — um método que não falha onde deveria falhar não está medindo nada.",
        "As afirmações sobre produtos de terceiros vêm exclusivamente de dados publicamente declarados: manifestos, descrições de lojas, APIs públicas e as próprias palavras dos fornecedores. A data de consulta é sempre informada.",
        "Nada foi descompilado. Nenhuma afirmação é feita sobre as intenções de qualquer fornecedor nem sobre dados efetivamente transmitidos — apenas sobre o que está publicamente declarado.",
    ],
    "warn_h3": "O que este site não fornece",
    "warn_p1": "Nada aqui constitui aconselhamento jurídico, de segurança, fiscal ou financeiro. As medições são execuções únicas com entradas específicas em um dia específico — relatos, não estudos. Software muda continuamente; um número de agosto de 2026 pode estar errado três meses depois. Verifique na fonte em tempo real antes de confiar em qualquer dado.",
    "warn_p2": "Em particular: um PDF produzido por captura de tela <strong>não é um documento eletrônico qualificado</strong>. Não carrega assinatura eletrônica qualificada, carimbo de tempo confiável nem cadeia de custódia. Registra o que um navegador exibiu em um determinado momento — adequado para os seus próprios registros, não equivalente à preservação de provas com valor notarial ou judicial.",
    "warn_p3": "Não se aceita responsabilidade por decisões tomadas com base no conteúdo aqui publicado, na medida permitida por lei. A responsabilidade legal por dolo e negligência grave permanece inalterada.",
    "warn_p4": "Os artigos deste site abordam ocasionalmente questões com dimensão jurídica — permissões, licenças, direitos autorais, o valor probatório de um registro. Nada disso constitui aconselhamento jurídico. Para uma situação específica, o caminho certo é a orientação de um profissional qualificado.",
    "links_h2": "Links externos",
    "links_p": "Os links apontam para conteúdos operados por terceiros. O conteúdo deles é responsabilidade desses terceiros; no momento da criação do link, nenhuma infração era aparente. Se uma página vinculada se tornar ilegal posteriormente, um aviso ao endereço de contato acima remove o link.",
    "corr_h2": "Correções",
    "corr_p": 'Se algo aqui estiver errado, diga e será corrigido — no próprio artigo, não como nota de rodapé anexada. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Abra uma issue</a> ou use o endereço de contato. Correções substantivas são registradas com sua data.',
    "reuse_h2": "Reutilização",
    "reuse_p": 'Os textos e dados deste site são publicados sob <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — a reutilização é bem-vinda com atribuição e um link. O software é outra questão e carrega a <a href="https://opensource.org/licenses/MIT">licença MIT</a>: uma licença de software cobre código, não prosa, por isso as duas são declaradas separadamente, e não juntas.',
}

# ------------------------------------------------------------------ Русский -
TEXTE["ru"] = {
    "h1": "О сайте и раскрытие информации",
    "lead": "Частная некоммерческая публикация. Кто её ведёт, как получаются цифры и что она сознательно не предлагает.",
    "what_h2": "Что это за сайт",
    "what_p": "Личная записная книжка, опубликованная открыто. Она содержит измерения браузерных инструментов и отчёты о разработке программного обеспечения. Она существует потому, что результаты полезнее в открытом доступе, чем в частном, — а не как бизнес.",
    "box_h3": "Некоммерческий, и структурно таков",
    "box_items": [
        "Здесь ничего не продаётся и ничего не предлагается к продаже.",
        "Никакой рекламы, спонсорских материалов, партнёрских ссылок, отслеживания и рассылок.",
        "Обсуждаемое программное обеспечение бесплатно и опубликовано под лицензией MIT.",
        "Никакие платежи не принимаются ни в какой форме, и никакие услуги не предлагаются за вознаграждение.",
        "Использование этого сайта не приводит к заключению какого-либо договора.",
    ],
    "who_h2": "Кто его ведёт",
    "op_dt": "Оператор",
    "op_dd": "Публикуется под псевдонимом <strong>Silence</strong> — тот же идентификатор, что используется для программного обеспечения на addons.mozilla.org и на GitHub как <code>Bubu89</code>.",
    "contact_dt": "Контакт",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> Сообщения читаются, и на них отвечают. По всему, что касается опубликованного содержимого, <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issue в репозитории</a> быстрее и оставляет публичную запись.',
    "legal_dt": "Юридический контакт",
    "legal_dd": "По вопросам, требующим полных данных оператора, — юридические уведомления, официальные запросы, требования о праве на ответ — пишите по указанному выше адресу. Личность и почтовый адрес раскрываются правомерному запрашивающему без промедления.",
    "disco_h2": "Раскрытие информации",
    "disco_p1": 'Этот сайт ведёт разработчик <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a>, который фигурирует в нескольких опубликованных измерениях. Эта связь указывается в каждой статье, где она имеет значение, а программное обеспечение открыто лежит в <code>/tools/</code>, а не скрывается за нейтральной подачей.',
    "disco_p2": "Ни один упомянутый здесь продукт не спонсировал, не рецензировал и не одобрял своё освещение. Никто не платит за размещение, потому что размещения для покупки не существует.",
    "fig_h2": "Как получаются цифры",
    "fig_items": [
        "Каждая цифра снабжена датой получения и инструментом, который её произвёл.",
        "Исходные данные публикуются рядом, чтобы цифры можно было проверить, а не принимать на веру.",
        "Каждый метод сначала запускается на эталонном случае: метод, который не даёт сбоя там, где должен, ничего не измеряет.",
        "Утверждения о продуктах третьих сторон основаны исключительно на публично заявленных данных: манифестах, описаниях в каталогах, открытых API и собственных заявлениях поставщиков. Дата обращения указывается всегда.",
        "Ничего не декомпилировалось. Не делается никаких утверждений о намерениях какого-либо поставщика или о фактически передаваемых данных — только о том, что публично заявлено.",
    ],
    "warn_h3": "Чего этот сайт не предоставляет",
    "warn_p1": "Ничто здесь не является юридической, финансовой, налоговой консультацией или консультацией по безопасности. Измерения — это единичные запуски с конкретными входными данными в конкретный день: отчёты, а не исследования. Программное обеспечение постоянно меняется; цифра от августа 2026 года может оказаться неверной три месяца спустя. Проверяйте по актуальному источнику, прежде чем на что-либо полагаться.",
    "warn_p2": "В частности: PDF, созданный путём захвата экрана, <strong>не является квалифицированным электронным документом</strong>. Он не содержит квалифицированной электронной подписи, доверенной метки времени и цепочки хранения. Он фиксирует то, что браузер отображал в определённый момент, — подходит для собственных записей, но не равнозначен нотариальному или судебному закреплению доказательств.",
    "warn_p3": "Ответственность за решения, принятые на основе опубликованного здесь содержимого, не принимается в пределах, допускаемых законом. Установленная законом ответственность за умысел и грубую неосторожность остаётся в силе.",
    "warn_p4": "Статьи на этом сайте иногда затрагивают вопросы с юридическим измерением — разрешения, лицензии, авторское право, доказательственную силу записи. Ничто из этого не является юридической консультацией. Для конкретной ситуации правильный путь — квалифицированная консультация.",
    "links_h2": "Внешние ссылки",
    "links_p": "Ссылки ведут на содержимое, которым управляют другие. За их содержимое отвечают они; на момент размещения ссылки нарушений не было видно. Если связанная страница позже станет противоправной, сообщение на указанный выше контактный адрес приведёт к удалению ссылки.",
    "corr_h2": "Исправления",
    "corr_p": 'Если здесь что-то неверно, скажите об этом — и это будет исправлено: в самой статье, а не в приложенной сноске. <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">Откройте issue</a> или воспользуйтесь контактным адресом. Существенные исправления отмечаются с указанием даты.',
    "reuse_h2": "Повторное использование",
    "reuse_p": 'Тексты и данные этого сайта опубликованы под лицензией <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> — повторное использование приветствуется с указанием авторства и ссылкой. Программное обеспечение — другой вопрос, и на него распространяется <a href="https://opensource.org/licenses/MIT">лицензия MIT</a>: лицензия на программное обеспечение покрывает код, а не прозу, поэтому обе указываются отдельно, а не вместе.',
}

# ------------------------------------------------------------------ 简体中文 -
TEXTE["zh-CN"] = {
    "h1": "关于与披露",
    "lead": "一份私人的非商业出版物。谁在运营它，数字是如何产生的，以及它刻意不提供什么。",
    "what_h2": "本网站是什么",
    "what_p": "一本公开的个人笔记。内容包含浏览器工具的测量结果和软件开发的工作报告。它之所以存在，是因为结果公开比私有更有用——而不是作为一门生意。",
    "box_h3": "非商业，而且是结构性的非商业",
    "box_items": [
        "这里不出售任何东西，也不提供任何待售之物。",
        "没有广告、没有赞助内容、没有联盟链接、没有跟踪、没有通讯订阅。",
        "所讨论的软件免费，并以 MIT 许可证发布。",
        "不以任何形式接受付款，也不提供任何有偿服务。",
        "使用本网站不会成立任何合同。",
    ],
    "who_h2": "运营者",
    "op_dt": "运营者",
    "op_dd": "以笔名 <strong>Silence</strong> 发布——与 addons.mozilla.org 上的软件以及 GitHub 上的 <code>Bubu89</code> 使用同一标识。",
    "contact_dt": "联系方式",
    "contact_dd": '<a href="mailto:contact@provinglab.dev">contact@provinglab.dev</a><br> 消息会被阅读并回复。对于涉及已发布内容的事项，<a href="https://github.com/Bubu89/full-page-pdf-snap/issues">在仓库中提交 issue</a> 更快，并会留下公开记录。',
    "legal_dt": "法律联系",
    "legal_dd": "对于需要运营者完整身份的事项——法律通知、正式请求、答辩权主张——请致函上述地址。我们会毫不拖延地向合法请求者披露身份和邮寄地址。",
    "disco_h2": "披露",
    "disco_p1": '本网站由 <a href="../tools/full-page-pdf-snap/">Full Page PDF Snap</a> 的开发者运营，该扩展出现在多项已发布的测量中。这一关系会在每篇相关文章中说明，软件公开置于 <code>/tools/</code> 之下，而非隐藏在中立的包装后面。',
    "disco_p2": "此处提及的任何产品均未赞助、审阅或批准对其的报道。没有人为刊登位置付费，因为根本没有可购买的刊登位置。",
    "fig_h2": "数字是如何产生的",
    "fig_items": [
        "每个数字都标注了获取日期和产生它的工具。",
        "原始数据一并发布，以便数字可以被检验，而不必被轻信。",
        "每种方法都先对参照用例运行——一个在该失败处不失败的方法，等于什么都没测量。",
        "关于第三方产品的陈述完全来自公开声明的数据：清单文件、商店描述、公开 API 以及提供商自己的表述。始终注明获取日期。",
        "未进行任何反编译。不对任何提供商的意图或实际传输的数据作任何断言——只涉及公开声明的内容。",
    ],
    "warn_h3": "本网站不提供的内容",
    "warn_p1": "这里的任何内容都不构成法律、安全、税务或财务建议。测量是特定日期对特定输入的单次运行——是报告，不是研究。软件不断变化；2026 年 8 月的数字三个月后可能是错的。在依赖任何内容之前，请与实时来源核对。",
    "warn_p2": "特别说明：通过屏幕捕获生成的 PDF <strong>不是合格电子文档</strong>。它不带有合格电子签名、可信时间戳，也没有保管链。它记录的是浏览器在某一时刻显示的内容——适合作为个人记录，但不等同于公证或司法级的证据保全。",
    "warn_p3": "在法律允许的范围内，不对基于本网站发布内容所作的决定承担任何责任。法律对故意和重大过失规定的责任不受影响。",
    "warn_p4": "本网站的文章偶尔涉及具有法律维度的问题——权限、许可证、版权、记录的证据效力。这些都不构成法律建议。对于具体情况，正确的途径是寻求合格的专业咨询。",
    "links_h2": "外部链接",
    "links_p": "链接指向由他人运营的内容。其内容由对方负责；在设置链接时未发现违法之处。如果被链接的页面后来变为违法，向上述联系地址发出通知即可移除该链接。",
    "corr_h2": "更正",
    "corr_p": '如果这里有错误，请指出，我们会更正——在文章正文中更正，而不是以附加脚注的形式。<a href="https://github.com/Bubu89/full-page-pdf-snap/issues">提交 issue</a> 或使用联系地址。实质性更正会注明日期。',
    "reuse_h2": "再利用",
    "reuse_p": '本网站的文本和数据以 <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> 发布——欢迎署名并附链接的再利用。软件则另当别论，采用 <a href="https://opensource.org/licenses/MIT">MIT 许可证</a>：软件许可证涵盖代码而非散文，因此两者分开声明，而非混为一谈。',
}
