#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Die Datensatz-Indexseite (data/) in neun Sprachen.

Gleiches Muster wie texte_indexseiten.py: ENGLISCH ist die Ausgangsfassung
(woertlich aus der bisherigen Seite uebernommen), Rendering ueber
build_data.py. Dateinamen sind href und sichtbarer Titel zugleich und bleiben
in jeder Sprache unveraendert — ebenso DOIs, URLs und Messwerte. Wer einen
Eintrag ergaenzt oder aendert, tut das HIER — die gebaute Seite nicht von
Hand editieren.
"""

SPRACHEN = ["en", "de", "es", "fr", "it", "ja", "pt-BR", "ru", "zh-CN"]
BASIS = "en"

TEXTE = {}

# --------------------------------------------------------------- English ----
TEXTE["en"] = {
    "h1": "Data",
    "lead": "The raw numbers behind the measurements, as JSON — including the control runs. Licensed CC BY 4.0, so they can be reused with attribution.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'A browser agent installing the extension from the store and triggering it, measured end to end on real Windows browsers: every step with what was clicked, what persisted on disk, and the failures — a hard kill after the Add click lost the Firefox install, and the per-user policy hive was ACL-locked on this machine. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Method as an agent skill</a>.',
         "figures": ["Firefox ESR + Chrome", "store installs verified on disk", "failures published"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Whether a synthetic input event at window-system level satisfies the activeTab gesture requirement: tabs visible to the extension before and after a keyboard command sent through X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Method and discussion</a>.',
         "figures": ["<b>0</b> tabs before", "<b>1</b> tab after", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'The counterpart: an agent driving the browser through CDP and the DOM only. The extension loads and its service worker runs, then every tab comes back with an empty url. <a href="../notes/what-an-agent-can-do-with-an-extension/">Method and discussion</a>.',
         "figures": ["<b>2/4</b> steps pass", "<b>0</b> tabs visible", "activeTab, no host permissions"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'For 150 cited web sources: live status, verdict, whether the Internet Archive holds a snapshot and how old it is. Cases where a service did not answer are marked as such rather than counted as negative. <a href="../measurements/web-citations-that-vanish/">Method and discussion</a>.',
         "figures": ["<b>19.3 %</b> gone", "<b>8.7 %</b> unarchived", "<b>603 d</b> median snapshot age"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'How much text survives when a full-page screenshot PDF goes through OCR, plus the full resolution series and a control run against unrelated text. <a href="../measurements/webpage-to-pdf-for-ocr/">Method and discussion</a>.',
         "figures": ["<b>92.6&nbsp;%</b> vocabulary recall", "<b>110 dpi</b> threshold", "<b>0.0&nbsp;%</b> control"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Declared permissions, host permissions, user counts and ratings for eight PDF and capture extensions, as retrieved from the Mozilla add-ons API. <a href="../measurements/pdf-extension-permissions/">Method and discussion</a>.',
         "figures": ["<b>8</b> extensions", "source: addons.mozilla.org API"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Twenty sources of a reading list through a citation endpoint, each with the fields returned and — for every source handed back — the response to a reader and to a browser, so a page\u2019s wall can be told from a reader\u2019s limit. <a href="../measurements/reading-list-to-bibliography/">Method and discussion</a>.',
         "figures": ["<b>10/20</b> complete records", "<b>1</b> bot defence", "<b>5</b> with nothing to declare"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Eighteen scholarly platforms, each checked for the citation data it declares about its own works, with every returned title verified against Crossref. <a href="../measurements/citation-by-platform/">Method and discussion</a>.',
         "figures": ["<b>11/18</b> returned data", "<b>10</b> with authors and year", "<b>8</b> matched Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'A mixed reading list of twelve sources: what an agent turned into citable records on its own, and the reason each of the remaining four was handed back. <a href="../measurements/citation-triage/">Method and discussion</a>.',
         "figures": ["<b>8/12</b> done by the agent", "<b>1.09 s</b> per source", "<b>4</b> named"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 page-saving extensions from the Mozilla add-ons API with their declared Android support, user counts and ratings. <a href="../measurements/android-capture-extensions/">Method and discussion</a>.',
         "figures": ["<b>248</b> extensions", "<b>60</b> declare Android", "<b>0</b> tested on a device"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Citation extraction measured against Citoid, the Wikimedia service built on the Zotero translators, across 18 works drawn at random — per source, with timings and every reported block re-checked from an unrelated network. <a href="../measurements/citation-extraction/">Method and discussion</a>.',
         "figures": ["<b>13/13</b> fields complete", "<b>0</b> false block reports", "<b>0.35 s</b> median"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'The same article through the browser\u2019s print export and through full-page capture: page count, broken sentences, file size, recovered text. <a href="../measurements/print-to-pdf-vs-screenshot/">Method and discussion</a>.',
         "figures": ["<b>26</b> pages against <b>1</b>", "<b>9</b> sentences cut", "<b>6×</b> file size"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">About &amp; disclosure</a> · Corrections: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">Disclaimer</a>',
}

# --------------------------------------------------------------- Deutsch ----
TEXTE["de"] = {
    "h1": "Daten",
    "lead": "Die rohen Zahlen hinter den Messungen, als JSON — einschließlich der Kontrollläufe. Lizenziert unter CC BY 4.0, also mit Namensnennung wiederverwendbar.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Ein Browser-Agent installiert die Erweiterung aus dem Store und löst sie aus, durchgehend gemessen in echten Windows-Browsern: jeder Schritt mit dem, was geklickt wurde, was auf der Platte blieb, und den Fehlschlägen — ein harter Kill nach dem Add-Klick kostete die Firefox-Installation, und der Policy-Zweig des Benutzers war auf diesem Rechner per ACL gesperrt. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Methode als Agent-Skill</a>.',
         "figures": ["Firefox ESR + Chrome", "Store-Installationen auf der Platte verifiziert", "Fehlschläge veröffentlicht"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Ob ein synthetisches Eingabeereignis auf Fenstersystem-Ebene die Geste für activeTab erfüllt: für die Erweiterung sichtbare Tabs vor und nach einem Tastaturbefehl über X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Methode und Diskussion</a>.',
         "figures": ["<b>0</b> Tabs davor", "<b>1</b> Tab danach", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'Das Gegenstück: ein Agent, der den Browser nur über CDP und das DOM steuert. Die Erweiterung lädt und ihr Service Worker läuft, dann kommt jeder Tab mit leerer url zurück. <a href="../notes/what-an-agent-can-do-with-an-extension/">Methode und Diskussion</a>.',
         "figures": ["<b>2/4</b> Schritte bestehen", "<b>0</b> Tabs sichtbar", "activeTab, keine Host-Rechte"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'Für 150 zitierte Webquellen: Live-Status, Urteil, ob das Internet Archive einen Schnappschuss hält und wie alt er ist. Fälle, in denen ein Dienst nicht antwortete, sind als solche markiert statt als negativ gezählt. <a href="../measurements/web-citations-that-vanish/">Methode und Diskussion</a>.',
         "figures": ["<b>19.3 %</b> verschwunden", "<b>8.7 %</b> nicht archiviert", "<b>603 d</b> medianes Schnappschuss-Alter"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Wie viel Text überlebt, wenn ein PDF aus Vollbild-Screenshots durch OCR läuft, plus die volle Auflösungsserie und ein Kontrolllauf gegen fremden Text. <a href="../measurements/webpage-to-pdf-for-ocr/">Methode und Diskussion</a>.',
         "figures": ["<b>92.6&nbsp;%</b> Wortschatz-Trefferquote", "<b>110 dpi</b> Schwelle", "<b>0.0&nbsp;%</b> Kontrolle"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Deklarierte Berechtigungen, Host-Berechtigungen, Nutzerzahlen und Bewertungen für acht PDF- und Capture-Erweiterungen, abgerufen über die Mozilla-Add-ons-API. <a href="../measurements/pdf-extension-permissions/">Methode und Diskussion</a>.',
         "figures": ["<b>8</b> Erweiterungen", "Quelle: addons.mozilla.org API"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Zwanzig Quellen einer Leseliste durch einen Zitations-Endpunkt, jede mit den zurückgegebenen Feldern und — für jede zurückgewiesene Quelle — die Antwort an einen Leser und an einen Browser, damit sich die Mauer einer Seite vom Limit eines Readers unterscheiden lässt. <a href="../measurements/reading-list-to-bibliography/">Methode und Diskussion</a>.',
         "figures": ["<b>10/20</b> vollständige Datensätze", "<b>1</b> Bot-Abwehr", "<b>5</b> ohne etwas zu deklarieren"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Achtzehn wissenschaftliche Plattformen, jede auf die Zitationsdaten geprüft, die sie über ihre eigenen Werke deklariert, jeder zurückgegebene Titel gegen Crossref verifiziert. <a href="../measurements/citation-by-platform/">Methode und Diskussion</a>.',
         "figures": ["<b>11/18</b> lieferten Daten", "<b>10</b> mit Autoren und Jahr", "<b>8</b> passten zu Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Eine gemischte Leseliste aus zwölf Quellen: was ein Agent allein in zitierfähige Datensätze verwandelte, und der Grund, warum jede der übrigen vier zurückgegeben wurde. <a href="../measurements/citation-triage/">Methode und Diskussion</a>.',
         "figures": ["<b>8/12</b> vom Agenten erledigt", "<b>1.09 s</b> pro Quelle", "<b>4</b> benannt"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 seiten-speichernde Erweiterungen aus der Mozilla-Add-ons-API mit ihrer deklarierten Android-Unterstützung, Nutzerzahlen und Bewertungen. <a href="../measurements/android-capture-extensions/">Methode und Diskussion</a>.',
         "figures": ["<b>248</b> Erweiterungen", "<b>60</b> deklarieren Android", "<b>0</b> auf einem Gerät getestet"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Zitationsextraktion gemessen gegen Citoid, den Wikimedia-Dienst auf Basis der Zotero-Übersetzer, über 18 zufällig gezogene Werke — pro Quelle, mit Zeitmessungen und jeder gemeldeten Blockade nachgeprüft aus einem fremden Netz. <a href="../measurements/citation-extraction/">Methode und Diskussion</a>.',
         "figures": ["<b>13/13</b> Felder vollständig", "<b>0</b> falsche Blockade-Meldungen", "<b>0.35 s</b> Median"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'Derselbe Artikel durch den Druckexport des Browsers und durch Vollbild-Capture: Seitenzahl, zerrissene Sätze, Dateigröße, zurückgewonnener Text. <a href="../measurements/print-to-pdf-vs-screenshot/">Methode und Diskussion</a>.',
         "figures": ["<b>26</b> Seiten gegen <b>1</b>", "<b>9</b> Sätze zerschnitten", "<b>6×</b> Dateigröße"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Über &amp; Offenlegung</a> · Korrekturen: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub Issues</a> · <a href="../disclaimer/">Haftungsausschluss</a>',
}

# --------------------------------------------------------------- Español ----
TEXTE["es"] = {
    "h1": "Datos",
    "lead": "Las cifras en bruto detrás de las mediciones, en JSON — incluidas las ejecuciones de control. Con licencia CC BY 4.0, para reutilizarlas con atribución.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Un agente de navegador instalando la extensión desde la tienda y activándola, medido de extremo a extremo en navegadores Windows reales: cada paso con lo que se pulsó, lo que quedó en disco y los fallos — una interrupción forzada tras el clic en Add perdió la instalación de Firefox, y la rama de directivas por usuario estaba bloqueada por ACL en esta máquina. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Método como skill de agente</a>.',
         "figures": ["Firefox ESR + Chrome", "instalaciones de tienda verificadas en disco", "fallos publicados"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Si un evento de entrada sintético a nivel del sistema de ventanas satisface el requisito de gesto de activeTab: pestañas visibles para la extensión antes y después de un comando de teclado enviado por X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Método y discusión</a>.',
         "figures": ["<b>0</b> pestañas antes", "<b>1</b> pestaña después", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'La contraparte: un agente que controla el navegador solo mediante CDP y el DOM. La extensión se carga y su service worker corre, luego cada pestaña vuelve con una url vacía. <a href="../notes/what-an-agent-can-do-with-an-extension/">Método y discusión</a>.',
         "figures": ["<b>2/4</b> pasos superados", "<b>0</b> pestañas visibles", "activeTab, sin permisos de host"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'Para 150 fuentes web citadas: estado en vivo, veredicto, si el Internet Archive conserva una captura y su antigüedad. Los casos en que un servicio no respondió se marcan como tales en lugar de contarse como negativos. <a href="../measurements/web-citations-that-vanish/">Método y discusión</a>.',
         "figures": ["<b>19.3 %</b> desaparecidas", "<b>8.7 %</b> sin archivar", "<b>603 d</b> mediana de antigüedad de la captura"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Cuánto texto sobrevive cuando un PDF de captura de página completa pasa por OCR, más la serie completa de resoluciones y una ejecución de control contra texto no relacionado. <a href="../measurements/webpage-to-pdf-for-ocr/">Método y discusión</a>.',
         "figures": ["<b>92.6&nbsp;%</b> de recuperación de vocabulario", "umbral de <b>110 dpi</b>", "<b>0.0&nbsp;%</b> control"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Permisos declarados, permisos de host, números de usuarios y valoraciones de ocho extensiones de PDF y captura, tal como se obtuvieron de la API de complementos de Mozilla. <a href="../measurements/pdf-extension-permissions/">Método y discusión</a>.',
         "figures": ["<b>8</b> extensiones", "fuente: API de addons.mozilla.org"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Veinte fuentes de una lista de lectura a través de un endpoint de citación, cada una con los campos devueltos y — para cada fuente rechazada — la respuesta a un lector y a un navegador, para distinguir el muro de una página del límite de un lector. <a href="../measurements/reading-list-to-bibliography/">Método y discusión</a>.',
         "figures": ["<b>10/20</b> registros completos", "<b>1</b> defensa contra bots", "<b>5</b> sin nada que declarar"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Dieciocho plataformas académicas, cada una comprobada por los datos de citación que declara sobre sus propias obras, con cada título devuelto verificado contra Crossref. <a href="../measurements/citation-by-platform/">Método y discusión</a>.',
         "figures": ["<b>11/18</b> devolvieron datos", "<b>10</b> con autores y año", "<b>8</b> coincidieron con Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Una lista de lectura mixta de doce fuentes: lo que un agente convirtió por sí solo en registros citables, y la razón por la que cada una de las cuatro restantes fue devuelta. <a href="../measurements/citation-triage/">Método y discusión</a>.',
         "figures": ["<b>8/12</b> hechas por el agente", "<b>1.09 s</b> por fuente", "<b>4</b> nombradas"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 extensiones para guardar páginas de la API de complementos de Mozilla con su soporte de Android declarado, números de usuarios y valoraciones. <a href="../measurements/android-capture-extensions/">Método y discusión</a>.',
         "figures": ["<b>248</b> extensiones", "<b>60</b> declaran Android", "<b>0</b> probadas en un dispositivo"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Extracción de citas medida contra Citoid, el servicio de Wikimedia construido sobre los traductores de Zotero, en 18 obras elegidas al azar — por fuente, con tiempos y cada bloqueo reportado verificado de nuevo desde una red no relacionada. <a href="../measurements/citation-extraction/">Método y discusión</a>.',
         "figures": ["<b>13/13</b> campos completos", "<b>0</b> reportes de bloqueo falsos", "mediana de <b>0.35 s</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'El mismo artículo a través de la exportación de impresión del navegador y de la captura de página completa: número de páginas, frases cortadas, tamaño de archivo, texto recuperado. <a href="../measurements/print-to-pdf-vs-screenshot/">Método y discusión</a>.',
         "figures": ["<b>26</b> páginas frente a <b>1</b>", "<b>9</b> frases cortadas", "<b>6×</b> tamaño de archivo"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Acerca de &amp; divulgación</a> · Correcciones: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues de GitHub</a> · <a href="../disclaimer/">Aviso legal</a>',
}

# --------------------------------------------------------------- Français ---
TEXTE["fr"] = {
    "h1": "Données",
    "lead": "Les chiffres bruts derrière les mesures, en JSON — y compris les passages de contrôle. Sous licence CC BY 4.0, réutilisables avec attribution.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Un agent de navigateur installant l\u2019extension depuis la boutique et la déclenchant, mesuré de bout en bout sur de vrais navigateurs Windows : chaque étape avec ce qui a été cliqué, ce qui est resté sur le disque et les échecs — un arrêt brutal après le clic sur Add a perdu l\u2019installation de Firefox, et la ruche de stratégie par utilisateur était verrouillée par ACL sur cette machine. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Méthode en tant que skill d\u2019agent</a>.',
         "figures": ["Firefox ESR + Chrome", "installations boutique vérifiées sur le disque", "échecs publiés"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Si un événement d\u2019entrée synthétique au niveau du système de fenêtres satisfait l\u2019exigence de geste d\u2019activeTab : onglets visibles pour l\u2019extension avant et après une commande clavier envoyée via X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Méthode et discussion</a>.',
         "figures": ["<b>0</b> onglet avant", "<b>1</b> onglet après", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'Le pendant : un agent pilotant le navigateur uniquement via CDP et le DOM. L\u2019extension se charge et son service worker tourne, puis chaque onglet revient avec une url vide. <a href="../notes/what-an-agent-can-do-with-an-extension/">Méthode et discussion</a>.',
         "figures": ["<b>2/4</b> étapes réussies", "<b>0</b> onglet visible", "activeTab, sans permissions d\u2019hôte"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'Pour 150 sources web citées : état en direct, verdict, si l\u2019Internet Archive détient un instantané et quel est son âge. Les cas où un service n\u2019a pas répondu sont marqués comme tels plutôt que comptés comme négatifs. <a href="../measurements/web-citations-that-vanish/">Méthode et discussion</a>.',
         "figures": ["<b>19.3 %</b> disparues", "<b>8.7 %</b> non archivées", "<b>603 j</b> âge médian des instantanés"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Quelle quantité de texte survit quand un PDF de capture pleine page passe par OCR, plus la série complète de résolutions et un passage de contrôle contre un texte sans rapport. <a href="../measurements/webpage-to-pdf-for-ocr/">Méthode et discussion</a>.',
         "figures": ["<b>92.6&nbsp;%</b> de rappel du vocabulaire", "seuil de <b>110 dpi</b>", "<b>0.0&nbsp;%</b> contrôle"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Permissions déclarées, permissions d\u2019hôte, nombres d\u2019utilisateurs et notes de huit extensions PDF et de capture, telles qu\u2019obtenues de l\u2019API des modules Mozilla. <a href="../measurements/pdf-extension-permissions/">Méthode et discussion</a>.',
         "figures": ["<b>8</b> extensions", "source : API addons.mozilla.org"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Vingt sources d\u2019une liste de lecture à travers un point de terminaison de citation, chacune avec les champs renvoyés et — pour chaque source rendue — la réponse à un lecteur et à un navigateur, pour distinguer le mur d\u2019une page de la limite d\u2019un lecteur. <a href="../measurements/reading-list-to-bibliography/">Méthode et discussion</a>.',
         "figures": ["<b>10/20</b> notices complètes", "<b>1</b> défense anti-bots", "<b>5</b> sans rien à déclarer"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Dix-huit plateformes savantes, chacune vérifiée pour les données de citation qu\u2019elle déclare sur ses propres œuvres, chaque titre renvoyé étant vérifié contre Crossref. <a href="../measurements/citation-by-platform/">Méthode et discussion</a>.',
         "figures": ["<b>11/18</b> ont renvoyé des données", "<b>10</b> avec auteurs et année", "<b>8</b> concordant avec Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Une liste de lecture mixte de douze sources : ce qu\u2019un agent a transformé seul en notices citables, et la raison pour laquelle chacune des quatre restantes a été rendue. <a href="../measurements/citation-triage/">Méthode et discussion</a>.',
         "figures": ["<b>8/12</b> traitées par l\u2019agent", "<b>1.09 s</b> par source", "<b>4</b> nommées"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 extensions de sauvegarde de pages issues de l\u2019API des modules Mozilla avec leur prise en charge Android déclarée, nombres d\u2019utilisateurs et notes. <a href="../measurements/android-capture-extensions/">Méthode et discussion</a>.',
         "figures": ["<b>248</b> extensions", "<b>60</b> déclarent Android", "<b>0</b> testée sur un appareil"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Extraction de citations mesurée contre Citoid, le service Wikimedia bâti sur les traducteurs Zotero, sur 18 œuvres tirées au hasard — par source, avec chronométrages et chaque blocage rapporté revérifié depuis un réseau sans rapport. <a href="../measurements/citation-extraction/">Méthode et discussion</a>.',
         "figures": ["<b>13/13</b> champs complets", "<b>0</b> faux rapport de blocage", "médiane de <b>0.35 s</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'Le même article via l\u2019export d\u2019impression du navigateur et via la capture pleine page : nombre de pages, phrases brisées, taille de fichier, texte récupéré. <a href="../measurements/print-to-pdf-vs-screenshot/">Méthode et discussion</a>.',
         "figures": ["<b>26</b> pages contre <b>1</b>", "<b>9</b> phrases coupées", "<b>6×</b> taille de fichier"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">À propos &amp; transparence</a> · Corrections : <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">tickets GitHub</a> · <a href="../disclaimer/">Mentions légales</a>',
}

# --------------------------------------------------------------- Italiano ---
TEXTE["it"] = {
    "h1": "Dati",
    "lead": "I numeri grezzi dietro le misurazioni, in JSON — comprese le corse di controllo. Con licenza CC BY 4.0, riutilizzabili con attribuzione.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Un agente browser che installa l\u2019estensione dallo store e la attiva, misurato dall\u2019inizio alla fine su veri browser Windows: ogni passaggio con ciò che è stato cliccato, ciò che è rimasto su disco e i fallimenti — una terminazione forzata dopo il clic su Add ha perso l\u2019installazione di Firefox, e l\u2019hive dei criteri per utente era bloccato da ACL su questa macchina. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Metodo come skill per agenti</a>.',
         "figures": ["Firefox ESR + Chrome", "installazioni dallo store verificate su disco", "fallimenti pubblicati"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Se un evento di input sintetico a livello di window system soddisfa il requisito del gesto di activeTab: schede visibili all\u2019estensione prima e dopo un comando da tastiera inviato tramite X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Metodo e discussione</a>.',
         "figures": ["<b>0</b> schede prima", "<b>1</b> scheda dopo", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'La controparte: un agente che guida il browser solo tramite CDP e il DOM. L\u2019estensione si carica e il suo service worker gira, poi ogni scheda torna con una url vuota. <a href="../notes/what-an-agent-can-do-with-an-extension/">Metodo e discussione</a>.',
         "figures": ["<b>2/4</b> passaggi riusciti", "<b>0</b> schede visibili", "activeTab, nessun permesso host"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'Per 150 fonti web citate: stato in tempo reale, verdetto, se l\u2019Internet Archive conserva uno snapshot e quanto è vecchio. I casi in cui un servizio non ha risposto sono segnati come tali invece di essere contati come negativi. <a href="../measurements/web-citations-that-vanish/">Metodo e discussione</a>.',
         "figures": ["<b>19.3 %</b> scomparse", "<b>8.7 %</b> non archiviate", "<b>603 g</b> età mediana dello snapshot"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Quanto testo sopravvive quando un PDF da screenshot a pagina intera passa per l\u2019OCR, più l\u2019intera serie di risoluzioni e una corsa di controllo contro testo estraneo. <a href="../measurements/webpage-to-pdf-for-ocr/">Metodo e discussione</a>.',
         "figures": ["<b>92.6&nbsp;%</b> di richiamo del vocabolario", "soglia di <b>110 dpi</b>", "<b>0.0&nbsp;%</b> controllo"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Permessi dichiarati, permessi host, numeri di utenti e valutazioni di otto estensioni PDF e di cattura, come recuperati dall\u2019API dei componenti aggiuntivi di Mozilla. <a href="../measurements/pdf-extension-permissions/">Metodo e discussione</a>.',
         "figures": ["<b>8</b> estensioni", "fonte: API addons.mozilla.org"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Venti fonti di una lista di lettura attraverso un endpoint di citazione, ognuna con i campi restituiti e — per ogni fonte rifiutata — la risposta a un lettore e a un browser, per distinguere il muro di una pagina dal limite di un reader. <a href="../measurements/reading-list-to-bibliography/">Metodo e discussione</a>.',
         "figures": ["<b>10/20</b> record completi", "<b>1</b> difesa anti-bot", "<b>5</b> senza nulla da dichiarare"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Diciotto piattaforme accademiche, ognuna verificata per i dati di citazione che dichiara sulle proprie opere, con ogni titolo restituito verificato contro Crossref. <a href="../measurements/citation-by-platform/">Metodo e discussione</a>.',
         "figures": ["<b>11/18</b> hanno restituito dati", "<b>10</b> con autori e anno", "<b>8</b> corrispondenti a Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Una lista di lettura mista di dodici fonti: cosa un agente ha trasformato da solo in record citabili, e il motivo per cui ciascuna delle quattro rimanenti è stata rifiutata. <a href="../measurements/citation-triage/">Metodo e discussione</a>.',
         "figures": ["<b>8/12</b> completate dall\u2019agente", "<b>1.09 s</b> per fonte", "<b>4</b> nominate"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 estensioni per salvare pagine dall\u2019API dei componenti aggiuntivi di Mozilla con il supporto Android dichiarato, numeri di utenti e valutazioni. <a href="../measurements/android-capture-extensions/">Metodo e discussione</a>.',
         "figures": ["<b>248</b> estensioni", "<b>60</b> dichiarano Android", "<b>0</b> testate su un dispositivo"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Estrazione di citazioni misurata contro Citoid, il servizio Wikimedia costruito sui traduttori di Zotero, su 18 opere estratte a caso — per fonte, con tempi e ogni blocco segnalato riverificato da una rete estranea. <a href="../measurements/citation-extraction/">Metodo e discussione</a>.',
         "figures": ["<b>13/13</b> campi completi", "<b>0</b> false segnalazioni di blocco", "mediana di <b>0.35 s</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'Lo stesso articolo attraverso l\u2019esportazione di stampa del browser e la cattura a pagina intera: numero di pagine, frasi spezzate, dimensione del file, testo recuperato. <a href="../measurements/print-to-pdf-vs-screenshot/">Metodo e discussione</a>.',
         "figures": ["<b>26</b> pagine contro <b>1</b>", "<b>9</b> frasi tagliate", "<b>6×</b> dimensione del file"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Informazioni &amp; trasparenza</a> · Correzioni: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issue su GitHub</a> · <a href="../disclaimer/">Esclusione di responsabilità</a>',
}

# ------------------------------------------------------------------ 日本語 --
TEXTE["ja"] = {
    "h1": "データ",
    "lead": "測定の裏にある生の数値を JSON で — コントロールランを含みます。CC BY 4.0 ライセンスのため、帰属表示付きで再利用できます。",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'ブラウザエージェントがストアから拡張機能をインストールして起動するまでを、実際の Windows ブラウザで端から端まで測定:クリックした内容、ディスクに残ったもの、失敗 — Add クリック後の強制終了で Firefox のインストールが失われ、このマシンではユーザーごとのポリシーハイブが ACL でロックされていました。<a href="/.well-known/agent-skills/install-as-a-counted-user.md">エージェントスキルとしての手法</a>。',
         "figures": ["Firefox ESR + Chrome", "ストアインストールをディスク上で検証", "失敗も公開"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'ウィンドウシステムレベルの合成入力イベントが activeTab のジェスチャ要件を満たすかどうか:X11 XTEST 経由で送ったキーボードコマンドの前後で拡張機能に見えるタブ。<a href="../notes/what-an-agent-can-do-with-an-extension/">手法と考察</a>。',
         "figures": ["実行前 <b>0</b> タブ", "実行後 <b>1</b> タブ", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": '対照例:CDP と DOM のみでブラウザを操作するエージェント。拡張機能は読み込まれサービスワーカーも動きますが、すべてのタブが空の url で返ってきます。<a href="../notes/what-an-agent-can-do-with-an-extension/">手法と考察</a>。',
         "figures": ["<b>2/4</b> ステップ通過", "見えるタブ <b>0</b>", "activeTab、ホスト権限なし"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": '引用された 150 のウェブソースについて:ライブ状態、判定、Internet Archive がスナップショットを保持しているかとその古さ。サービスが応答しなかったケースは、ネガティブとして数えずその旨を明示しています。<a href="../measurements/web-citations-that-vanish/">手法と考察</a>。',
         "figures": ["<b>19.3 %</b> 消失", "<b>8.7 %</b> 未アーカイブ", "スナップショット年齢の中央値 <b>603 日</b>"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'フルページスクリーンショットの PDF を OCR に通したときにどれだけのテキストが残るか。全解像度シリーズと、無関係なテキストに対するコントロールラン付き。<a href="../measurements/webpage-to-pdf-for-ocr/">手法と考察</a>。',
         "figures": ["語彙の再現率 <b>92.6&nbsp;%</b>", "閾値 <b>110 dpi</b>", "コントロール <b>0.0&nbsp;%</b>"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": '8 つの PDF・キャプチャ系拡張機能について、宣言された権限、ホスト権限、ユーザー数、評価を Mozilla アドオン API から取得したもの。<a href="../measurements/pdf-extension-permissions/">手法と考察</a>。',
         "figures": ["拡張機能 <b>8</b> 件", "出典:addons.mozilla.org API"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": '読書リストの 20 ソースを引用エンドポイントに通した結果。各ソースについて返されたフィールドと、返却された各ソースについてリーダーへの応答とブラウザへの応答 — ページの壁とリーダーの制限を区別できるようにしています。<a href="../measurements/reading-list-to-bibliography/">手法と考察</a>。',
         "figures": ["完全なレコード <b>10/20</b>", "ボット防御 <b>1</b>", "申告事項なし <b>5</b>"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": '18 の学術プラットフォームについて、それぞれが自プラットフォームの著作物に対して宣言している引用データを調査。返されたすべてのタイトルを Crossref と照合済みです。<a href="../measurements/citation-by-platform/">手法と考察</a>。',
         "figures": ["データを返したのは <b>11/18</b>", "著者・年つき <b>10</b>", "Crossref と一致 <b>8</b>"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": '12 ソースの混在した読書リスト:エージェントが単独で引用可能なレコードに変換できたものと、残り 4 件がそれぞれ返却された理由。<a href="../measurements/citation-triage/">手法と考察</a>。',
         "figures": ["エージェント処理 <b>8/12</b>", "1 ソースあたり <b>1.09 s</b>", "理由付き <b>4</b> 件"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": 'Mozilla アドオン API からのページ保存系拡張機能 248 件。宣言された Android 対応、ユーザー数、評価付き。<a href="../measurements/android-capture-extensions/">手法と考察</a>。',
         "figures": ["拡張機能 <b>248</b> 件", "Android 対応を宣言 <b>60</b>", "実機テスト <b>0</b>"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Zotero トランスレーター上に構築された Wikimedia のサービス Citoid を基準にした引用抽出の測定。ランダムに選んだ 18 著作物について、ソースごとに、タイミングと、報告されたブロックすべてを無関係のネットワークから再検証。<a href="../measurements/citation-extraction/">手法と考察</a>。',
         "figures": ["フィールド完全 <b>13/13</b>", "ブロック誤報 <b>0</b>", "中央値 <b>0.35 s</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": '同じ記事をブラウザの印刷エクスポートとフルページキャプチャで:ページ数、途切れた文、ファイルサイズ、復元されたテキスト。<a href="../measurements/print-to-pdf-vs-screenshot/">手法と考察</a>。',
         "figures": ["<b>26</b> ページ対 <b>1</b>", "切断された文 <b>9</b>", "ファイルサイズ <b>6 倍</b>"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">概要と開示</a> · 修正: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">免責事項</a>',
}

# --------------------------------------------------------------- Português --
TEXTE["pt-BR"] = {
    "h1": "Dados",
    "lead": "Os números brutos por trás das medições, em JSON — incluindo as rodadas de controle. Licenciados sob CC BY 4.0, para reutilização com atribuição.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Um agente de navegador instalando a extensão da loja e acionando-a, medido de ponta a ponta em navegadores Windows reais: cada etapa com o que foi clicado, o que persistiu em disco e as falhas — um encerramento forçado após o clique em Add perdeu a instalação do Firefox, e a hive de políticas por usuário estava bloqueada por ACL nesta máquina. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Método como skill de agente</a>.',
         "figures": ["Firefox ESR + Chrome", "instalações da loja verificadas em disco", "falhas publicadas"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Se um evento de entrada sintético no nível do sistema de janelas satisfaz o requisito de gesto do activeTab: abas visíveis para a extensão antes e depois de um comando de teclado enviado pelo X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Método e discussão</a>.',
         "figures": ["<b>0</b> abas antes", "<b>1</b> aba depois", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'A contrapartida: um agente controlando o navegador apenas via CDP e o DOM. A extensão carrega e seu service worker roda, depois cada aba retorna com uma url vazia. <a href="../notes/what-an-agent-can-do-with-an-extension/">Método e discussão</a>.',
         "figures": ["<b>2/4</b> etapas aprovadas", "<b>0</b> abas visíveis", "activeTab, sem permissões de host"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'Para 150 fontes web citadas: status ao vivo, veredito, se o Internet Archive guarda um snapshot e qual a sua idade. Casos em que um serviço não respondeu são marcados como tal em vez de contados como negativos. <a href="../measurements/web-citations-that-vanish/">Método e discussão</a>.',
         "figures": ["<b>19.3 %</b> desaparecidas", "<b>8.7 %</b> não arquivadas", "idade mediana do snapshot de <b>603 d</b>"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Quanto texto sobrevive quando um PDF de captura de página inteira passa por OCR, mais a série completa de resoluções e uma rodada de controle contra texto não relacionado. <a href="../measurements/webpage-to-pdf-for-ocr/">Método e discussão</a>.',
         "figures": ["<b>92.6&nbsp;%</b> de recall de vocabulário", "limiar de <b>110 dpi</b>", "<b>0.0&nbsp;%</b> controle"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Permissões declaradas, permissões de host, contagens de usuários e avaliações de oito extensões de PDF e captura, conforme obtidas da API de complementos da Mozilla. <a href="../measurements/pdf-extension-permissions/">Método e discussão</a>.',
         "figures": ["<b>8</b> extensões", "fonte: API addons.mozilla.org"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Vinte fontes de uma lista de leitura por um endpoint de citação, cada uma com os campos retornados e — para cada fonte devolvida — a resposta a um leitor e a um navegador, para distinguir o muro de uma página do limite de um leitor. <a href="../measurements/reading-list-to-bibliography/">Método e discussão</a>.',
         "figures": ["<b>10/20</b> registros completos", "<b>1</b> defesa contra bots", "<b>5</b> sem nada a declarar"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Dezoito plataformas acadêmicas, cada uma verificada quanto aos dados de citação que declara sobre as próprias obras, com cada título retornado verificado contra o Crossref. <a href="../measurements/citation-by-platform/">Método e discussão</a>.',
         "figures": ["<b>11/18</b> retornaram dados", "<b>10</b> com autores e ano", "<b>8</b> bateram com o Crossref"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Uma lista de leitura mista de doze fontes: o que um agente transformou sozinho em registros citáveis, e o motivo pelo qual cada uma das quatro restantes foi devolvida. <a href="../measurements/citation-triage/">Método e discussão</a>.',
         "figures": ["<b>8/12</b> feitas pelo agente", "<b>1.09 s</b> por fonte", "<b>4</b> nomeadas"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 extensões de salvar páginas da API de complementos da Mozilla com seu suporte a Android declarado, contagens de usuários e avaliações. <a href="../measurements/android-capture-extensions/">Método e discussão</a>.',
         "figures": ["<b>248</b> extensões", "<b>60</b> declaram Android", "<b>0</b> testadas em um dispositivo"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Extração de citações medida contra o Citoid, o serviço da Wikimedia construído sobre os tradutores do Zotero, em 18 obras sorteadas ao acaso — por fonte, com tempos e cada bloqueio relatado reverificado a partir de uma rede não relacionada. <a href="../measurements/citation-extraction/">Método e discussão</a>.',
         "figures": ["<b>13/13</b> campos completos", "<b>0</b> falsos relatórios de bloqueio", "mediana de <b>0.35 s</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'O mesmo artigo pela exportação de impressão do navegador e pela captura de página inteira: número de páginas, frases quebradas, tamanho do arquivo, texto recuperado. <a href="../measurements/print-to-pdf-vs-screenshot/">Método e discussão</a>.',
         "figures": ["<b>26</b> páginas contra <b>1</b>", "<b>9</b> frases cortadas", "<b>6×</b> tamanho do arquivo"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">Sobre &amp; transparência</a> · Correções: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues no GitHub</a> · <a href="../disclaimer/">Aviso legal</a>',
}

# ------------------------------------------------------------------ Русский -
TEXTE["ru"] = {
    "h1": "Данные",
    "lead": "Сырые числа, стоящие за измерениями, в JSON — включая контрольные прогоны. Лицензия CC BY 4.0: можно использовать повторно с указанием авторства.",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": 'Браузерный агент устанавливает расширение из магазина и запускает его, измерено от начала до конца на реальных браузерах Windows: каждый шаг с тем, что было нажато, что осталось на диске, и с отказами — жёсткое завершение после клика Add потеряло установку Firefox, а ветка пользовательских политик на этой машине была заблокирована ACL. <a href="/.well-known/agent-skills/install-as-a-counted-user.md">Метод как скилл агента</a>.',
         "figures": ["Firefox ESR + Chrome", "установки из магазина проверены на диске", "отказы опубликованы"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": 'Удовлетворяет ли синтетическое событие ввода на уровне оконной системы требованию жеста для activeTab: вкладки, видимые расширению, до и после клавиатурной команды, отправленной через X11 XTEST. <a href="../notes/what-an-agent-can-do-with-an-extension/">Метод и обсуждение</a>.',
         "figures": ["<b>0</b> вкладок до", "<b>1</b> вкладка после", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": 'Противоположный случай: агент управляет браузером только через CDP и DOM. Расширение загружается и его service worker работает, но каждая вкладка возвращается с пустым url. <a href="../notes/what-an-agent-can-do-with-an-extension/">Метод и обсуждение</a>.',
         "figures": ["<b>2/4</b> шагов пройдено", "видимых вкладок <b>0</b>", "activeTab, без хост-разрешений"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": 'По 150 процитированным веб-источникам: текущий статус, вердикт, хранит ли Internet Archive снимок и какого он возраста. Случаи, когда сервис не ответил, помечены как таковые, а не посчитаны отрицательными. <a href="../measurements/web-citations-that-vanish/">Метод и обсуждение</a>.',
         "figures": ["<b>19.3 %</b> исчезли", "<b>8.7 %</b> не заархивированы", "медианный возраст снимка <b>603 дн.</b>"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": 'Сколько текста выживает, когда PDF из полностраничных скриншотов проходит через OCR, плюс полная серия разрешений и контрольный прогон на постороннем тексте. <a href="../measurements/webpage-to-pdf-for-ocr/">Метод и обсуждение</a>.',
         "figures": ["полнота словаря <b>92.6&nbsp;%</b>", "порог <b>110 dpi</b>", "контроль <b>0.0&nbsp;%</b>"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": 'Заявленные разрешения, хост-разрешения, число пользователей и оценки восьми PDF- и захватывающих расширений, полученные через API дополнений Mozilla. <a href="../measurements/pdf-extension-permissions/">Метод и обсуждение</a>.',
         "figures": ["<b>8</b> расширений", "источник: API addons.mozilla.org"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": 'Двадцать источников из списка чтения через конечную точку цитирования, каждый с возвращёнными полями и — для каждого возвращённого источника — ответ ридеру и браузеру, чтобы отличить стену страницы от лимита ридера. <a href="../measurements/reading-list-to-bibliography/">Метод и обсуждение</a>.',
         "figures": ["полных записей <b>10/20</b>", "защита от ботов <b>1</b>", "нечего заявить <b>5</b>"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": 'Восемнадцать научных платформ, каждая проверена на предмет данных цитирования, которые она заявляет о собственных работах; каждый возвращённый заголовок сверен с Crossref. <a href="../measurements/citation-by-platform/">Метод и обсуждение</a>.',
         "figures": ["вернули данные <b>11/18</b>", "с авторами и годом <b>10</b>", "совпали с Crossref <b>8</b>"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": 'Смешанный список чтения из двенадцати источников: что агент сам превратил в цитируемые записи, и причина, по которой каждый из оставшихся четырёх был возвращён. <a href="../measurements/citation-triage/">Метод и обсуждение</a>.',
         "figures": ["сделано агентом <b>8/12</b>", "<b>1.09 с</b> на источник", "названо <b>4</b>"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '248 расширений для сохранения страниц из API дополнений Mozilla с заявленной поддержкой Android, числом пользователей и оценками. <a href="../measurements/android-capture-extensions/">Метод и обсуждение</a>.',
         "figures": ["<b>248</b> расширений", "заявляют Android <b>60</b>", "проверено на устройстве <b>0</b>"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": 'Извлечение цитирований, измеренное против Citoid — сервиса Викимедиа, построенного на трансляторах Zotero, — на 18 случайно выбранных работах: по каждому источнику, с замерами времени, каждый заявленный блок перепроверен из независимой сети. <a href="../measurements/citation-extraction/">Метод и обсуждение</a>.',
         "figures": ["полей полностью <b>13/13</b>", "ложных сообщений о блоке <b>0</b>", "медиана <b>0.35 с</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": 'Одна и та же статья через печатный экспорт браузера и через полностраничный захват: число страниц, разорванные предложения, размер файла, восстановленный текст. <a href="../measurements/print-to-pdf-vs-screenshot/">Метод и обсуждение</a>.',
         "figures": ["<b>26</b> страниц против <b>1</b>", "обрезано предложений <b>9</b>", "размер файла <b>6×</b>"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">О сайте и раскрытие</a> · Исправления: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">issues на GitHub</a> · <a href="../disclaimer/">Отказ от ответственности</a>',
}

# ------------------------------------------------------------------ 简体中文 -
TEXTE["zh-CN"] = {
    "h1": "数据",
    "lead": "测量背后的原始数字,以 JSON 提供——包括对照运行。采用 CC BY 4.0 许可,署名即可复用。",
    "items": [
        {"href": "2026-08-03-agent-install-and-capture.json",
         "title": "2026-08-03-agent-install-and-capture.json",
         "text": '一个浏览器代理从商店安装扩展并触发它,在真实 Windows 浏览器上端到端测量:每一步记录了点击了什么、磁盘上留下了什么以及失败——Add 点击后的强制终止丢失了 Firefox 的安装,而这台机器上的每用户策略配置单元被 ACL 锁定。<a href="/.well-known/agent-skills/install-as-a-counted-user.md">以代理技能形式提供的方法</a>。',
         "figures": ["Firefox ESR + Chrome", "商店安装已在磁盘上验证", "失败也已公开"]},
        {"href": "2026-08-03-agent-real-gesture.json",
         "title": "2026-08-03-agent-real-gesture.json",
         "text": '窗口系统级别的合成输入事件是否满足 activeTab 的手势要求:通过 X11 XTEST 发送键盘命令前后扩展可见的标签页。<a href="../notes/what-an-agent-can-do-with-an-extension/">方法与讨论</a>。',
         "figures": ["之前 <b>0</b> 个标签页", "之后 <b>1</b> 个标签页", "Chromium 145"]},
        {"href": "2026-08-03-agent-uses-the-extension.json",
         "title": "2026-08-03-agent-uses-the-extension.json",
         "text": '对照组:一个只通过 CDP 和 DOM 驱动浏览器的代理。扩展加载成功、service worker 也在运行,但每个标签页返回的 url 都为空。<a href="../notes/what-an-agent-can-do-with-an-extension/">方法与讨论</a>。',
         "figures": ["<b>2/4</b> 步通过", "可见标签页 <b>0</b>", "activeTab,无主机权限"]},
        {"href": "2026-08-02-quellen-archiv.json",
         "title": "2026-08-02-quellen-archiv.json",
         "text": '针对 150 个被引用的网络来源:实时状态、判定、Internet Archive 是否保存快照及其保存时间。服务未应答的情形被如实标记,而不是计为阴性。<a href="../measurements/web-citations-that-vanish/">方法与讨论</a>。',
         "figures": ["<b>19.3 %</b> 已消失", "<b>8.7 %</b> 未存档", "快照年龄中位数 <b>603 天</b>"]},
        {"href": "2026-08-01-ocr-recall.json",
         "title": "2026-08-01-ocr-recall.json",
         "text": '整页截图 PDF 经过 OCR 后有多少文本存活,外加完整的分辨率系列和针对无关文本的对照运行。<a href="../measurements/webpage-to-pdf-for-ocr/">方法与讨论</a>。',
         "figures": ["词汇召回率 <b>92.6&nbsp;%</b>", "阈值 <b>110 dpi</b>", "对照 <b>0.0&nbsp;%</b>"]},
        {"href": "2026-08-01-extension-permissions.json",
         "title": "2026-08-01-extension-permissions.json",
         "text": '八个 PDF 与截图类扩展的已声明权限、主机权限、用户数和评分,取自 Mozilla 附加组件 API。<a href="../measurements/pdf-extension-permissions/">方法与讨论</a>。',
         "figures": ["<b>8</b> 个扩展", "来源:addons.mozilla.org API"]},
        {"href": "2026-08-03-reading-list-to-bibliography.json",
         "title": "2026-08-03-reading-list-to-bibliography.json",
         "text": '阅读清单中的二十个来源经过引用端点处理,每个来源附有返回的字段,以及——对每个被退回的来源——对阅读器和浏览器各自的响应,从而区分页面的墙与阅读器的限额。<a href="../measurements/reading-list-to-bibliography/">方法与讨论</a>。',
         "figures": ["完整记录 <b>10/20</b>", "机器人防御 <b>1</b>", "无可声明 <b>5</b>"]},
        {"href": "2026-08-03-citation-by-platform.json",
         "title": "2026-08-03-citation-by-platform.json",
         "text": '十八个学术平台,逐一检查其就自身作品声明的引用数据,每个返回的标题都与 Crossref 核对。<a href="../measurements/citation-by-platform/">方法与讨论</a>。',
         "figures": ["返回数据 <b>11/18</b>", "含作者和年份 <b>10</b>", "与 Crossref 一致 <b>8</b>"]},
        {"href": "2026-08-03-citation-triage.json",
         "title": "2026-08-03-citation-triage.json",
         "text": '一个十二个来源的混合阅读清单:代理自行转化了多少条可引用记录,以及其余四个各自被退回的原因。<a href="../measurements/citation-triage/">方法与讨论</a>。',
         "figures": ["代理完成 <b>8/12</b>", "每来源 <b>1.09 秒</b>", "已注明原因 <b>4</b>"]},
        {"href": "2026-08-02-android-capture-extensions.json",
         "title": "2026-08-02-android-capture-extensions.json",
         "text": '来自 Mozilla 附加组件 API 的 248 个网页保存类扩展,附其声明的 Android 支持、用户数和评分。<a href="../measurements/android-capture-extensions/">方法与讨论</a>。',
         "figures": ["<b>248</b> 个扩展", "声明支持 Android <b>60</b>", "实机测试 <b>0</b>"]},
        {"href": "2026-08-02-citation-extraction.json",
         "title": "2026-08-02-citation-extraction.json",
         "text": '以 Citoid(维基媒体基于 Zotero 翻译器构建的服务)为基准测量的引用提取,随机抽取 18 部作品——逐来源,含耗时,并且每条报告的阻断都从未知网络复核。<a href="../measurements/citation-extraction/">方法与讨论</a>。',
         "figures": ["字段完整 <b>13/13</b>", "误报阻断 <b>0</b>", "中位数 <b>0.35 秒</b>"]},
        {"href": "2026-08-01-print-vs-screenshot.json",
         "title": "2026-08-01-print-vs-screenshot.json",
         "text": '同一篇文章分别经过浏览器打印导出和整页捕获:页数、断句、文件大小、恢复的文本。<a href="../measurements/print-to-pdf-vs-screenshot/">方法与讨论</a>。',
         "figures": ["<b>26</b> 页对 <b>1</b> 页", "截断句子 <b>9</b> 句", "文件大小 <b>6 倍</b>"]},
    ],
    "foot": '<a href="../">← Proving Lab</a> · <a href="../about/">关于与披露</a> · 更正: <a href="https://github.com/Bubu89/full-page-pdf-snap/issues">GitHub issues</a> · <a href="../disclaimer/">免责声明</a>',
}
